#!/usr/bin/env python3
"""Report glyph coverage of the game fonts for English, Russian and Uzbek.

For every font in game/assets/fonts/ it checks the cmap (and that mapped glyphs
are not empty) for these character sets:

    Basic Latin            U+0020-U+007E
    Latin-1 Supplement     U+00A0-U+00FF
    Russian Cyrillic       U+0410-U+044F (A-ya) + U+0401 / U+0451 (Yo yo)
    Uzbek punctuation      U+02BB, U+02BC, U+2018, U+2019, U+00AB, U+00BB, U+2014
    Uzbek Cyrillic extras  U+040E/045E, U+049A/049B, U+0492/0493, U+04B2/04B3 (informational)

Usage (from the repository root):
    python3 tools/fonts/check_coverage.py                    # print + write docs/FONT_COVERAGE.md
    python3 tools/fonts/check_coverage.py --out -            # print only
Exit code is 0; missing glyphs are reported, not treated as errors, because
Godot falls back to Noto Sans for any glyph a display font lacks.
"""
from __future__ import annotations

import argparse
import datetime as dt
import sys
import unicodedata
from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[2]
FONT_DIR = ROOT / "game" / "assets" / "fonts"
DEFAULT_OUT = ROOT / "docs" / "FONT_COVERAGE.md"

SETS = [
    ("Basic Latin", [chr(c) for c in range(0x20, 0x7F)]),
    ("Latin-1 Supplement", [chr(c) for c in range(0xA0, 0x100)]),
    ("Russian Cyrillic (А–я, Ёё)", [chr(c) for c in range(0x410, 0x450)] + ["Ё", "ё"]),
    ("Uzbek punctuation (ʻ ʼ ‘ ’ « » —)", ["ʻ", "ʼ", "‘", "’", "«", "»", "—"]),
    ("Uzbek Cyrillic extras (Ўў Ққ Ғғ Ҳҳ, info)", ["Ў", "ў", "Қ", "қ", "Ғ", "ғ", "Ҳ", "ҳ"]),
]
WHITESPACE = {" ", " ", "­"}  # legitimately empty / invisible glyphs

FONT_ROLES = {
    "CormorantGaramond": "Display (titles, plaques)",
    "NotoSans": "UI and body, fallback for every other font",
    "Caveat": "Handwriting (notebook)",
}


def glyph_is_empty(font: TTFont, glyph_name: str) -> bool:
    if "glyf" in font:
        g = font["glyf"][glyph_name]
        return g.numberOfContours == 0
    if "CFF " in font:
        cs = font["CFF "].cff.topDictIndex[0].CharStrings[glyph_name]
        cs.decompile()
        return len(cs.program) <= 2  # just width + endchar
    return False


def check(path: Path) -> list[tuple[str, int, int, list[str]]]:
    font = TTFont(path)
    cmap = font.getBestCmap()
    rows = []
    for name, chars in SETS:
        missing = []
        for ch in chars:
            gname = cmap.get(ord(ch))
            if gname is None or (ch not in WHITESPACE and glyph_is_empty(font, gname)):
                missing.append(ch)
        rows.append((name, len(chars) - len(missing), len(chars), missing))
    return rows


def fmt_missing(missing: list[str]) -> str:
    if not missing:
        return ""
    parts = []
    for ch in missing[:24]:
        try:
            label = unicodedata.name(ch).title()
        except ValueError:
            label = "?"
        parts.append(f"`U+{ord(ch):04X}` {label}")
    more = f" … (+{len(missing) - 24})" if len(missing) > 24 else ""
    return ", ".join(parts) + more


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(DEFAULT_OUT), help="markdown output path, or - for stdout only")
    ap.add_argument("--fonts", default=str(FONT_DIR), help="font directory")
    args = ap.parse_args()

    fonts = sorted(p for p in Path(args.fonts).iterdir() if p.suffix.lower() in (".ttf", ".otf"))
    if not fonts:
        print(f"no fonts in {args.fonts}", file=sys.stderr)
        return 1

    lines = [
        "# Font Coverage Report",
        "",
        f"_Generated by `tools/fonts/check_coverage.py` on {dt.date.today().isoformat()} (fontTools cmap check;"
        " a glyph counts only if it is mapped and has outlines)._",
        "",
        "| Font file | Role | " + " | ".join(n for n, _ in SETS) + " |",
        "|---|---|" + "---|" * len(SETS),
    ]
    details = []
    lacks_uz = []
    for p in fonts:
        rows = check(p)
        role = next((r for k, r in FONT_ROLES.items() if p.name.startswith(k)), "")
        cells = []
        for name, ok, total, missing in rows:
            mark = "✅" if ok == total else ("⚠️" if ok else "❌")
            cells.append(f"{mark} {ok}/{total}")
        lines.append(f"| `{p.name}` | {role} | " + " | ".join(cells) + " |")
        for name, ok, total, missing in rows:
            if missing:
                details.append(f"- **{p.name}**, {name}: missing {fmt_missing(missing)}")
                if name.startswith("Uzbek punctuation") and any(c in missing for c in ("ʻ", "ʼ")):
                    lacks_uz.append(p.name)
        print(f"{p.name}: " + "; ".join(f"{n} {ok}/{t}" for n, ok, t, _ in rows))

    lines += ["", "## Missing glyphs", ""]
    lines += details if details else ["None. Every font covers every checked set."]
    lines += ["", "## Fallback policy", ""]
    if lacks_uz:
        lines.append(
            "These fonts lack the Uzbek modifier letters ʻ (U+02BB) and/or ʼ (U+02BC): "
            + ", ".join(f"`{n}`" for n in sorted(set(lacks_uz)))
            + ". Configure **Noto Sans** (`NotoSans-Variable.ttf`) as a fallback font on them in Godot "
            "(`FontFile.fallbacks` / `FontVariation.fallbacks`), so Uzbek words such as oʻ and gʻ render "
            "correctly in every language."
        )
    else:
        lines.append("All fonts include ʻ (U+02BB) and ʼ (U+02BC).")
    lines.append(
        "Noto Sans is the universal fallback: it covers Basic Latin, Latin-1, full Russian Cyrillic and all Uzbek"
        " punctuation and Cyrillic extras checked above, so attach it as the last fallback of the display and"
        " handwriting fonts."
    )
    lines.append("")
    text = "\n".join(lines)
    if args.out != "-":
        Path(args.out).write_text(text)
        print(f"wrote {args.out}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
