#!/usr/bin/env python3
"""Generates game/src/ui/license_texts.gd: the licence texts that Settings -> About -> Licenses shows
(the OFL text of the two fonts, the MIT notices of the two purchase plugins). They live in a GDScript constant so that
every export includes them (a loose .txt is not exported). Run again when the font licence files change:
    python3 tools/ui/make_license_texts.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FONTS = ROOT / "game" / "assets" / "fonts"
OUT = ROOT / "game" / "src" / "ui" / "license_texts.gd"

MIT = """Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."""

ITEMS = [
    ("NOTO_SANS", (FONTS / "NotoSans-OFL.txt").read_text().strip()),
    ("CORMORANT", (FONTS / "CormorantGaramond-OFL.txt").read_text().strip()),
    ("GODOT_GOOGLE_PLAY_BILLING", "Copyright (c) 2020 Godot Engine contributors\n\n" + MIT),
    ("GODOT_IOS_PLUGIN_IAP", "Copyright (c) 2025-2026 Hiroki Taira\n\n" + MIT),
]

out = ["class_name LicenseTexts", "extends RefCounted",
       "## GENERATED by tools/ui/make_license_texts.py: do not edit by hand.",
       "## Licence texts shown in Settings -> About -> Licenses.", ""]
for name, text in ITEMS:
    assert '"""' not in text
    out.append(f'const {name} := r"""{text}"""')
    out.append("")
OUT.write_text("\n".join(out))
print("wrote", OUT, sum(len(t) for _, t in ITEMS), "chars")
