# -*- coding: utf-8 -*-
"""Core strings: (key, en, ru, uz). Uzbek is Latin only, using ʻ (U+02BB) for oʻ/gʻ and ʼ (U+02BC).
Order of languages is fixed: EN (default) → RU → UZ."""

S = [
# ---------------------------------------------------------------- brand / chapters
("game.title", "MYSTERY ROOM", "MYSTERY ROOM", "MYSTERY ROOM"),
("game.subtitle", "The Forgotten Institute", "Забытый институт", "Unutilgan institut"),
("chapter.label", "Chapter %d", "Глава %d", "%d-bob"),
("chapter.ch1.title", "The Locked Laboratory", "Запертая лаборатория", "Qulflangan laboratoriya"),
("chapter.ch1.subtitle", "Laboratory 7", "Лаборатория 7", "7-laboratoriya"),
("chapter.ch2.title", "The Missing Scientist", "Пропавший учёный", "Gʻoyib boʻlgan olim"),
("chapter.ch2.subtitle", "The Archive", "Архив", "Arxiv"),
("chapter.ch3.title", "The Underground Facility", "Подземный комплекс", "Yer osti majmuasi"),
("chapter.ch3.subtitle", "Below the Institute", "Под институтом", "Institut ostida"),
("chapter.ch4.title", "The Experiment", "Эксперимент", "Tajriba"),
("chapter.ch4.subtitle", "The Array Hall", "Зал Решётки", "Panjara zali"),

# ---------------------------------------------------------------- main UI
("ui.continue", "Continue", "Продолжить", "Davom etish"),
("ui.new_game", "New Game", "Новая игра", "Yangi oʻyin"),
("ui.chapters", "Chapters", "Главы", "Boblar"),
("ui.settings", "Settings", "Настройки", "Sozlamalar"),
("ui.credits", "Credits", "Авторы", "Mualliflar"),
("ui.quit", "Quit", "Выход", "Chiqish"),
("ui.quit_confirm", "Quit the game? Your progress is saved.", "Выйти из игры? Прогресс сохранён.", "Oʻyindan chiqasizmi? Hammasi saqlangan."),
("ui.back", "Back", "Назад", "Orqaga"),
("ui.close", "Close", "Закрыть", "Yopish"),
("ui.resume", "Resume", "Продолжить", "Davom etish"),
("ui.pause", "Pause", "Пауза", "Pauza"),
("ui.main_menu", "Main Menu", "Главное меню", "Bosh menyu"),
("ui.yes", "Yes", "Да", "Ha"),
("ui.no", "No", "Нет", "Yoʻq"),
("ui.confirm", "Confirm", "Подтвердить", "Tasdiqlash"),
("ui.cancel", "Cancel", "Отмена", "Bekor qilish"),
("ui.on", "On", "Вкл.", "Yoniq"),
("ui.off", "Off", "Выкл.", "Oʻchiq"),
("ui.tap_to_continue", "Tap to continue", "Нажмите, чтобы продолжить", "Davom etish uchun bosing"),
("ui.skip", "Skip", "Пропустить", "Oʻtkazib yuborish"),
("ui.new_game_confirm", "Start a new game? Your current progress will be lost.", "Начать новую игру? Текущий прогресс будет потерян.", "Yangi oʻyin boshlansinmi? Joriy oʻyin oʻchib ketadi."),
("ui.choose_language", "Choose your language", "Выберите язык", "Tilni tanlang"),
("ui.language", "Language", "Язык", "Til"),
("ui.music", "Music", "Музыка", "Musiqa"),
("ui.sfx", "Sound effects", "Звуковые эффекты", "Tovush effektlari"),
("ui.ambience", "Ambience", "Атмосфера", "Muhit tovushlari"),
("ui.safe_graphics", "Simplified graphics", "Упрощённая графика", "Soddalashtirilgan grafika"),
("msg.safe_graphics_on", "Simplified graphics are on after a problem while loading. You can change this in Settings.", "После сбоя при загрузке включена упрощённая графика. Изменить можно в настройках.", "Yuklashdagi nosozlikdan soʻng soddalashtirilgan grafika yoqildi. Sozlamalarda oʻzgartirish mumkin."),
("ui.text_size", "Text size", "Размер текста", "Matn oʻlchami"),
("ui.haptics", "Vibration", "Вибрация", "Tebranish"),
("ui.reduce_motion", "Reduce camera motion", "Меньше движения камеры", "Kamera harakatini kamaytirish"),
("ui.look_sensitivity", "Look sensitivity", "Чувствительность обзора", "Kamera sezgirligi"),
("ui.reset_settings", "Reset settings", "Сбросить настройки", "Sozlamalarni tiklash"),
("ui.delete_save", "Delete progress", "Удалить прогресс", "Saqlangan oʻyinni oʻchirish"),
("ui.delete_save_confirm", "Delete all saved progress? This cannot be undone.", "Удалить весь сохранённый прогресс? Это действие необратимо.", "Saqlangan oʻyin butunlay oʻchirilsinmi? Buni qaytarib boʻlmaydi."),
("ui.restore", "Restore purchases", "Восстановить покупки", "Xaridlarni tiklash"),
("ui.restored", "Purchases restored.", "Покупки восстановлены.", "Xaridlar tiklandi."),
("ui.privacy", "Privacy policy", "Политика конфиденциальности", "Maxfiylik siyosati"),
("ui.brightness", "Brightness", "Яркость", "Yorqinlik"),
("ui.unlock", "Unlock the full game", "Открыть полную игру", "Toʻliq oʻyinni ochish"),
("ui.unlock_desc", "One purchase unlocks the remaining chapters. No ads, no subscriptions.", "Одна покупка открывает остальные главы. Без рекламы и подписок.", "Bitta xarid qolgan boblarni ochadi. Reklama va obunasiz."),
("ui.store_unavailable", "The store is not available yet. New chapters are coming soon.", "Магазин пока недоступен. Новые главы скоро появятся.", "Doʻkon hozircha mavjud emas. Yangi boblar tez orada chiqadi."),
("ui.purchase_ok", "Thank you! The full game is unlocked.", "Спасибо! Полная игра открыта.", "Rahmat! Toʻliq oʻyin ochildi."),
# in-app purchase (docs/MONETIZATION.md): the purchase screen and the store's answers
("ui.buy", "Unlock", "Открыть", "Ochish"),
("ui.buy_for", "Unlock for %s", "Открыть за %s", "Ochish (%s)"),
("ui.unlock_includes", "Chapters 3–4. Chapters 1–2 stay free.", "Главы 3–4. Главы 1–2 остаются бесплатными.", "3–4-boblar. 1–2-boblar bepul boʻlib qoladi."),
("ui.owned", "Unlocked", "Открыто", "Ochilgan"),
("ui.store_working", "Waiting for the store…", "Ожидание ответа магазина…", "Doʻkon javobi kutilmoqda…"),
("ui.reset_purchase", "Reset purchase (test)", "Сбросить покупку (тест)", "Xaridni tozalash (test)"),
("store.pending", "Your payment is pending. The chapters unlock as soon as the store confirms it.", "Платёж ожидает подтверждения. Главы откроются, как только магазин его подтвердит.", "Toʻlov tasdiqlanishi kutilmoqda. Doʻkon tasdiqlashi bilan boblar ochiladi."),
("store.cancelled", "Purchase cancelled.", "Покупка отменена.", "Xarid bekor qilindi."),
("store.network", "Could not reach the store. Check your internet connection and try again.", "Не удалось связаться с магазином. Проверьте подключение к интернету и попробуйте ещё раз.", "Doʻkonga ulanib boʻlmadi. Internet aloqasini tekshirib, qayta urinib koʻring."),
("store.billing_unavailable", "Purchases are not available on this device or account.", "Покупки недоступны на этом устройстве или в этом аккаунте.", "Bu qurilma yoki akkauntda xaridlar mavjud emas."),
("store.not_found", "The full game is not available in your store yet. Please try again later.", "Полная игра пока недоступна в вашем магазине. Попробуйте позже.", "Toʻliq oʻyin hozircha doʻkoningizda mavjud emas. Keyinroq urinib koʻring."),
("store.already_owned", "You already own the full game. It is unlocked.", "Полная игра у вас уже есть. Она открыта.", "Toʻliq oʻyin sizda allaqachon bor. U ochildi."),
("store.unverified", "The store could not verify this purchase. Try Restore purchases later.", "Магазин не смог подтвердить эту покупку. Попробуйте позже «Восстановить покупки».", "Doʻkon bu xaridni tasdiqlay olmadi. Keyinroq «Xaridlarni tiklash»ni bosing."),
("store.error", "The purchase could not be completed. Please try again later.", "Не удалось завершить покупку. Попробуйте позже.", "Xaridni yakunlab boʻlmadi. Keyinroq qayta urinib koʻring."),
("store.busy", "The store is still busy with your last request. Please wait.", "Магазин ещё обрабатывает предыдущий запрос. Подождите, пожалуйста.", "Doʻkon oldingi soʻrovni hali bajarmoqda. Biroz kuting."),
("store.restore_none", "No previous purchase was found for this account.", "Покупок для этого аккаунта не найдено.", "Bu akkaunt uchun avvalgi xarid topilmadi."),
("store.restore_failed", "Could not restore purchases. Check your internet connection and try again.", "Не удалось восстановить покупки. Проверьте подключение к интернету и попробуйте ещё раз.", "Xaridlarni tiklab boʻlmadi. Internet aloqasini tekshirib, qayta urinib koʻring."),
("store.reset_done", "Test purchase reset on this device. You can buy it again.", "Тестовая покупка сброшена на этом устройстве. Её можно купить снова.", "Test xaridi bu qurilmada tozalandi. Uni yana sotib olish mumkin."),
("store.reset_sandbox_hint", "Reset on this device only. To buy it again, clear the sandbox account's purchase history in App Store Connect (Users and Access, Sandbox).", "Сброшено только на этом устройстве. Чтобы купить снова, очистите историю покупок sandbox-аккаунта в App Store Connect (Users and Access, Sandbox).", "Faqat shu qurilmada tozalandi. Qayta sotib olish uchun App Store Connect saytida sandbox akkauntining xaridlar tarixini tozalang (Users and Access, Sandbox)."),
("ui.free", "Free", "Бесплатно", "Bepul"),
("ui.locked", "Locked", "Закрыто", "Yopiq"),
("ui.coming_soon", "Coming soon", "Скоро", "Tez orada"),
("ui.completed", "Completed", "Пройдено", "Yakunlangan"),
("ui.play", "Play", "Играть", "Oʻynash"),
("ui.saved", "Progress saved", "Прогресс сохранён", "Oʻyin saqlandi"),
("ui.save_failed", "Could not save progress", "Не удалось сохранить прогресс", "Oʻyinni saqlab boʻlmadi"),
("ui.loading", "Loading…", "Загрузка…", "Yuklanmoqda…"),
("ui.version", "Version %s", "Версия %s", "Versiya %s"),

# ---------------------------------------------------------------- in-game HUD
("ui.hint", "Hint", "Подсказка", "Maslahat"),
("ui.hint_more", "Stronger hint (2/3)", "Яснее (2/3)", "Aniqroq (2/3)"),
("ui.hint_answer", "Show the answer (3/3)", "Показать ответ (3/3)", "Javobni ochish (3/3)"),
("ui.hint_level", "Hint %d of 3", "Подсказка %d из 3", "%d-maslahat (3 tadan)"),
("ui.hint_level_answer", "Hint 3 of 3: the answer", "Подсказка 3 из 3: ответ", "3-maslahat (3 tadan): javob"),
("ui.inspect", "Inspect", "Осмотреть", "Koʻrib chiqish"),
("ui.combine", "Combine", "Объединить", "Birlashtirish"),
("ui.use", "Use", "Использовать", "Ishlatish"),
("ui.read", "Read", "Читать", "Oʻqish"),
("ui.inventory_empty", "Your pockets are empty.", "Карманы пусты.", "Choʻntaklaringiz boʻsh."),
("ui.bag", "Bag", "Сумка", "Sumka"),
("ui.combine_prompt", "Tap an item to combine with: %s", "Выберите предмет для объединения с: %s", "Birlashtirish uchun buyumni tanlang: %s"),
("ui.use_prompt", "Tap where to use: %s", "Нажмите, где использовать: %s", "Qayerda ishlatishni tanlang: %s"),
("ui.uv_on", "UV light", "УФ-свет", "UB nur"),
("ui.uv_drag", "Drag to shine the UV lamp", "Ведите пальцем, чтобы светить УФ-лампой", "UB chiroqni yoritish uchun barmoqni suring"),
("ui.page", "Page %d / %d", "Стр. %d / %d", "%d / %d-sahifa"),
("ui.notebook", "Notebook", "Блокнот", "Daftar"),
("ui.journal", "Journal", "Журнал", "Jurnal"),
("ui.new_entry", "New note in the journal", "Новая запись в журнале", "Jurnalda yangi yozuv"),
("ui.item_added", "Found: %s", "Найдено: %s", "Topildi: %s"),
("ui.shard_found", "Lumen shard %d / 5", "Осколок Люмена %d / 5", "Lumen boʻlagi %d / 5"),
("ui.puzzle_solved", "Solved", "Решено", "Yechildi"),
("ui.choice_prompt", "The crystal lens hums softly in the projector. Leyla's light is fading.", "Кристаллическая линза тихо гудит в проекторе. Свет Лейлы угасает.", "Billur linza proyektorda mayin gʻuvillaydi. Leylaning nuri soʻnmoqda."),
("ui.take_lens", "Take the lens", "Забрать линзу", "Linzani olish"),
("ui.leave_lens", "Leave it for her", "Оставить ей", "Unga qoldirish"),
("ui.chapter_complete", "Chapter complete", "Глава пройдена", "Bob yakunlandi"),
("ui.time", "Time", "Время", "Vaqt"),
("ui.hints_used", "Hints used", "Подсказок", "Maslahatlar"),
("ui.puzzles", "Puzzles solved", "Головоломок решено", "Yechilgan jumboqlar"),
("ui.shards", "Lumen shards", "Осколки Люмена", "Lumen boʻlaklari"),
("ui.next_chapter", "Next chapter", "Следующая глава", "Keyingi bob"),
("ui.to_be_continued", "To be continued…", "Продолжение следует…", "Davomi bor…"),
("ui.achievement", "Achievement: %s", "Достижение: %s", "Yutuq: %s"),
("ach.light_remembers", "Light Remembers", "Свет помнит", "Yorugʻlik eslaydi"),
("ach.no_hints_ch1", "Clear Mind", "Ясный ум", "Tiniq aql"),

# ---------------------------------------------------------------- onboarding
("tut.look", "Drag to look around.", "Проведите пальцем, чтобы осмотреться.", "Atrofga qarash uchun barmoqni suring."),
("tut.tap", "Tap objects to examine them.", "Нажимайте на предметы, чтобы рассмотреть их.", "Buyumlarni koʻrish uchun ularga bosing."),
("tut.zoom", "Pinch to zoom.", "Разведите пальцы, чтобы приблизить.", "Yaqinlashtirish uchun ikki barmoqni kering."),
("tut.back", "Tap the back arrow in the corner to step back.", "Нажмите стрелку «назад» в углу, чтобы вернуться.", "Orqaga qaytish uchun burchakdagi strelkani bosing."),
("tut.inventory", "Found items go into your bag, bottom left. Tap the bag to open it, an item to pick it up, the same item again to inspect it.", "Найденные предметы попадают в сумку внизу слева. Нажмите на сумку, чтобы открыть её, на предмет — чтобы взять его, на него же ещё раз — чтобы осмотреть.", "Topilgan buyumlar pastki chap burchakdagi sumkaga tushadi. Sumkani ochish uchun unga, buyumni olish uchun buyumga bosing; koʻrish uchun shu buyumga yana bosing."),
("tut.use", "With an item selected, tap the place where you want to use it.", "Выбрав предмет, нажмите туда, где хотите его использовать.", "Buyumni tanlab, uni ishlatmoqchi boʻlgan joyga bosing."),
("tut.combine", "Select an item, press Combine, then tap another item.", "Выберите предмет, нажмите «Объединить», затем другой предмет.", "Buyumni tanlang, «Birlashtirish»ni bosing, soʻng boshqa buyumni tanlang."),
("tut.hint", "Stuck? The lamp icon gives a hint — gently at first.", "Застряли? Значок лампы даст подсказку — сначала мягкую.", "Qiyin boʻldimi? Chiroq belgisi maslahat beradi — avval yengilroq."),

# ---------------------------------------------------------------- intro / outro
("intro.1", "Meridian Institute of Resonant Physics.\nSealed since 14 November 1979.", "Институт резонансной физики «Меридиан».\nЗакрыт с 14 ноября 1979 года.", "«Meridian» rezonans fizikasi instituti.\n1979-yil 14-noyabrdan beri yopiq."),
("intro.2", "A parcel came for you. Inside: an old laboratory badge and a single line.\n“Laboratory 7. Please finish what I could not.”", "Вам пришла посылка. Внутри — старый пропуск лаборатории и одна строка:\n«Лаборатория 7. Пожалуйста, закончи то, что не смогла я».", "Sizga posilka keldi. Ichida — eski laboratoriya guvohnomasi va bir qator yozuv:\n«7-laboratoriya. Iltimos, men tugata olmagan ishni oxiriga yetkazing»."),
("outro.echo", "For a moment, the laboratory is 1979 again.", "На мгновение лаборатория снова в 1979 году.", "Bir lahzaga laboratoriya yana 1979-yilga qaytadi."),
("outro.listening", "The Array is listening again.", "Решётка снова слушает.", "Panjara yana tinglamoqda."),
("epi.take", "You pocket the crystal lens. It is warm — and somewhere far below, something answers its hum.", "Вы прячете линзу в карман. Она тёплая — и где-то глубоко внизу что-то отвечает на её гул.", "Billur linzani choʻntagingizga solasiz. U iliq — va qayerdadir chuqurda nimadir uning gʻuvillashiga javob beradi."),
("epi.leave", "You leave the lens to her. As the door closes behind you, the desk lamp flickers once, like a goodbye.", "Вы оставляете линзу ей. Когда дверь закрывается за вами, настольная лампа мигает — словно прощаясь.", "Linzani unga qoldirasiz. Eshik ortingizdan yopilganda stol chirogʻi bir bor miltillaydi — xuddi xayrlashgandek."),
("epi.shards", "Five shards — five fragments of a single night. The Array knows you now.", "Пять осколков — пять фрагментов одной ночи. Теперь Решётка знает вас.", "Beshta boʻlak — bitta tunning besh parchasi. Endi Panjara sizni taniydi."),
("epi.postmark", "On the train home you look at the parcel again. The postmark reads: 14 XI 1979.", "В поезде вы снова смотрите на посылку. На штемпеле: 14 XI 1979.", "Uyga qaytayotgan poyezdda posilkaga yana qaraysiz. Pochta muhrida: 14 XI 1979."),

# ---------------------------------------------------------------- settings panel sections (UI redesign)
("ui.sec_sound", "Sound", "Звук", "Tovush"),
("ui.sec_display", "Display & comfort", "Экран и комфорт", "Ekran va qulaylik"),
("ui.sec_other", "Other", "Прочее", "Boshqa"),
("ui.safe_graphics_desc", "Fewer effects and shadows: for older phones, or after a crash.", "Меньше эффектов и теней: для старых телефонов или после сбоя.", "Kamroq effekt va soya: eski telefonlar uchun yoki nosozlikdan soʻng."),
("ui.text_normal", "Normal", "Обычный", "Oddiy"),
("ui.text_large", "Large", "Крупный", "Katta"),
("ui.text_xl", "Extra large", "Очень крупный", "Juda katta"),
("ui.zoom_hint", "Pinch or double-tap to zoom", "Сведите пальцы или дважды коснитесь, чтобы увеличить", "Kattalashtirish uchun ikki barmoq bilan torting yoki ikki marta bosing"),
]
