# -*- coding: utf-8 -*-
"""Chapter 2 "The Missing Scientist" — Records Archive B. (key, en, ru, uz). Uzbek: Latin only, ʻ for oʻ/gʻ.
Puzzle-critical information is never carried by these texts alone (numbers/symbols are on the objects)."""

S = [
# ---------------------------------------------------------------- items
("item.leyla_badge.name", "Leyla's lab badge", "Пропуск Лейлы", "Leylaning guvohnomasi"),
("item.leyla_badge.desc", "Laboratory 7 · Staff no. 0417 · Dr. L. Rahimova. It came in the parcel.", "Лаборатория 7 · Табельный № 0417 · Д-р Л. Рахимова. Он был в посылке.", "7-laboratoriya · Xodim № 0417 · Dr. L. Rahimova. U posilkada kelgan."),
("item.index_card.name", "Index card 0417", "Карточка 0417", "0417-kartochka"),
("item.index_card.desc", "Leyla's personnel card. Eight positions along the top edge; some are notched.", "Личная карточка Лейлы. Восемь позиций по верхнему краю, часть из них с вырезами.", "Leylaning shaxsiy kartochkasi. Yuqori chetida sakkizta joy bor, baʼzilari kesilgan."),
("item.blank_card.name", "Blank request card", "Чистый бланк запроса", "Boʻsh soʻrov kartasi"),
("item.blank_card.desc", "A request card for the closed stacks. It must be punched first.", "Бланк запроса в закрытое хранение. Сначала его нужно пробить.", "Yopiq fondga soʻrov kartasi. Avval uni teshish kerak."),
("item.request_card.name", "Punched request card", "Пробитый бланк запроса", "Teshilgan soʻrov kartasi"),
("item.request_card.desc", "Ready to travel by tube.", "Готов к отправке по трубе.", "Quvur orqali joʻnatishga tayyor."),
("item.personnel_file.name", "Leyla's personnel file", "Личное дело Лейлы", "Leylaning shaxsiy ishi"),
("item.personnel_file.desc", "A thin folder. A letter from 1998 is clipped inside.", "Тонкая папка. Внутри приколото письмо 1998 года.", "Yupqa papka. Ichida 1998-yilgi maktub qistirilgan."),
("item.locker_key.name", "Locker key", "Ключ от шкафчика", "Shkafcha kaliti"),
("item.locker_key.desc", "A small key on a brass tag: 9.", "Маленький ключ на латунной бирке: 9.", "Jez yorliqli kichik kalit: 9."),
("item.pocket_receiver.name", "Pocket receiver", "Карманный приёмник", "Choʻntak qabul qilgichi"),
("item.pocket_receiver.desc", "Leyla's direction-finding receiver. Its needle climbs near whatever it listens for.", "Пеленгационный приёмник Лейлы. Стрелка поднимается рядом с тем, что он слышит.", "Leylaning yoʻnalish topuvchi qabul qilgichi. U eshitadigan narsa yaqinida mili koʻtariladi."),
("item.tape_1996.name", "Reel · 1996", "Катушка · 1996", "Gʻaltak · 1996"),
("item.tape_1996.desc", "A tape reel in Leyla's hand. The label reads 1996 · 4.75.", "Катушка с плёнкой, подписанная рукой Лейлы: 1996 · 4.75.", "Leyla qoʻli bilan yozilgan lenta gʻaltagi: 1996 · 4.75."),
("item.tape_1997.name", "Reel · 1997", "Катушка · 1997", "Gʻaltak · 1997"),
("item.tape_1997.desc", "A tape reel in Leyla's hand. The label reads 1997 · 4.75.", "Катушка с плёнкой, подписанная рукой Лейлы: 1997 · 4.75.", "Leyla qoʻli bilan yozilgan lenta gʻaltagi: 1997 · 4.75."),
("item.tape_1998.name", "Reel · 1998", "Катушка · 1998", "Gʻaltak · 1998"),
("item.tape_1998.desc", "A tape reel in Leyla's hand. The label reads 1998 · 4.75.", "Катушка с плёнкой, подписанная рукой Лейлы: 1998 · 4.75.", "Leyla qoʻli bilan yozilgan lenta gʻaltagi: 1998 · 4.75."),
("item.film_reel.name", "Film reel", "Бобина с плёнкой", "Kinolenta bobinasi"),
("item.film_reel.desc", "Strand's 1979 film, spliced back together.", "Фильм Странда 1979 года, снова склеенный.", "Strandning 1979-yilgi filmi, qayta yelimlangan."),
("item.crystal_blank_1.name", "Blank Lumen crystal", "Чистый кристалл Люмена", "Boʻsh Lumen billuri"),
("item.crystal_blank_1.desc", "A clear crystal. It remembers the first sharp image that falls on it.", "Прозрачный кристалл. Он запоминает первое чёткое изображение, которое на него упадёт.", "Tiniq billur. Ustiga tushgan birinchi aniq tasvirni eslab qoladi."),
("item.crystal_blank_2.name", "Blank Lumen crystal", "Чистый кристалл Люмена", "Boʻsh Lumen billuri"),
("item.crystal_blank_2.desc", "A clear crystal. It remembers the first sharp image that falls on it.", "Прозрачный кристалл. Он запоминает первое чёткое изображение, которое на него упадёт.", "Tiniq billur. Ustiga tushgan birinchi aniq tasvirni eslab qoladi."),
("item.crystal_sign.name", "Crystal: Leyla's sign", "Кристалл: знак Лейлы", "Billur: Leyla belgisi"),
("item.crystal_sign.desc", "It keeps Leyla's sign: a crescent with three dots.", "В нём хранится знак Лейлы: полумесяц с тремя точками.", "Unda Leyla belgisi saqlangan: uch nuqtali yarim oy."),
("item.crystal_mark.name", "Crystal: Strand's mark", "Кристалл: знак Странда", "Billur: Strand belgisi"),
("item.crystal_mark.desc", "It keeps the Institute's mark: a ring and a meridian.", "В нём хранится знак института: кольцо и меридиан.", "Unda institut belgisi saqlangan: halqa va meridian."),
("item.emblem_slide.name", "Emblem slide", "Слайд с эмблемой", "Emblemali slayd"),
("item.emblem_slide.desc", "A glass lantern slide with the Institute's mark.", "Стеклянный диапозитив со знаком института.", "Institut belgisi tushirilgan shisha diapozitiv."),
("item.strand_key.name", "Strand's key", "Ключ Странда", "Strandning kaliti"),
("item.strand_key.desc", "Heavy brass with a star. It opens the Array Hall.", "Тяжёлая латунь со звездой. Он открывает Зал Решётки.", "Yulduzli ogʻir jez kalit. U Panjara zalini ochadi."),
("item.leyla_key.name", "Leyla's key", "Ключ Лейлы", "Leylaning kaliti"),
("item.leyla_key.desc", "Plain steel with a crescent. It opens the crystal vaults.", "Простая сталь с полумесяцем. Он открывает хранилища кристаллов.", "Yarim oy tushirilgan oddiy poʻlat kalit. U billur omborlarini ochadi."),
# ---------------------------------------------------------------- places (view captions)
("obj2.hall", "Records Archive B", "Архив документов «Б»", "«B» hujjatlar arxivi"),
("obj2.catalogue", "Card catalogue — staff 0000–0999", "Картотека — сотрудники 0000–0999", "Kartoteka — xodimlar 0000–0999"),
("obj2.sign_catalogue", "CARD CATALOGUE", "КАРТОТЕКА", "KARTOTEKA"),
("obj2.compressor", "Tube compressor", "Компрессор пневмопочты", "Pnevmatik pochta kompressori"),
("obj2.station", "Pneumatic tube station", "Станция пневмопочты", "Pnevmatik pochta stansiyasi"),
("obj2.chart", "Routing chart", "Схема маршрутов", "Yoʻnalishlar sxemasi"),
("obj2.desk", "Archivist's desk", "Стол архивариуса", "Arxivchi stoli"),
("obj2.punch", "Card punch", "Перфоратор карт", "Karta teshgich"),
("obj2.deck", "Tape deck", "Магнитофон", "Magnitofon"),
("obj2.lockers", "Staff lockers", "Шкафчики сотрудников", "Xodimlar shkafchalari"),
("obj2.stacks", "The stacks", "Стеллажи", "Javonlar"),
("obj2.grille", "Ventilation grille", "Вентиляционная решётка", "Shamollatish panjarasi"),
("obj2.ledger", "A row of ledgers", "Ряд гроссбухов", "Hisob daftarlari qatori"),
("obj2.reading", "Reading table", "Читальный стол", "Mutolaa stoli"),
("obj2.hatch", "A hatch in the floor", "Люк в полу", "Poldagi lyuk"),
("obj2.booth_door", "Projection booth — dial lock", "Кинобудка — дисковый замок", "Kinobudka — diskli qulf"),
("obj2.booth", "Projection booth", "Кинобудка", "Kinobudka"),
("obj2.splicer", "Film splicer", "Склеечный пресс", "Kinolenta yelimlagichi"),
("obj2.projector", "Film projector", "Кинопроектор", "Kinoproyektor"),
("obj2.slides", "Slide cabinet", "Шкаф для слайдов", "Slaydlar javoni"),
("obj2.slide_projector", "Slide projector", "Диапроектор", "Diaproyektor"),
("obj2.screen", "Projection screen", "Проекционный экран", "Proyeksiya ekrani"),
("obj2.vault", "Archive vault — dual light lock", "Хранилище архива — двойной световой замок", "Arxiv seyfxonasi — qoʻsh yorugʻlik qulfi"),
("obj2.vault_open", "Archive vault", "Хранилище архива", "Arxiv seyfxonasi"),
("obj2.shutter", "Fire shutter — jammed", "Противопожарная штора — заклинило", "Yongʻinga qarshi toʻsiq — tiqilib qolgan"),
# ---------------------------------------------------------------- messages (msg.* = layout-tested)
("msg.c2_shutter", "The fire shutter crashes down behind you.", "Позади с грохотом падает противопожарная штора.", "Ortingizda yongʻinga qarshi toʻsiq gursillab tushdi."),
("msg.c2_card_other", "Card %s: a stranger's file. You put it back.", "Карточка %s: чужое дело. Вы кладёте её обратно.", "%s-kartochka: begona odamning ishi. Uni joyiga qaytardingiz."),
("msg.c2_card_leyla", "Card 0417: Rahimova, Leyla. Laboratory 7.", "Карточка 0417: Рахимова Лейла. Лаборатория 7.", "0417-kartochka: Rahimova Leyla. 7-laboratoriya."),
("msg.c2_pressure_ok", "The compressor wheezes to life. The station lamp turns green.", "Компрессор оживает с хрипом. Лампа станции загорается зелёным.", "Kompressor xirillab ishga tushdi. Stansiya chirogʻi yashil yondi."),
("msg.c2_valves_locked", "The valves hold the pressure now.", "Вентили теперь держат давление.", "Endi ventillar bosimni ushlab turibdi."),
("msg.c2_gauges", "Gauge P: %s.  Gauge F: %s.", "Манометр P: %s.  Манометр F: %s.", "P manometri: %s.  F manometri: %s."),
("msg.c2_on_mark", "on its green mark", "на зелёной метке", "yashil belgida"),
("msg.c2_off_mark", "off the mark", "мимо метки", "belgidan tashqarida"),
("msg.c2_punch_empty", "The punch is empty. It needs a blank card.", "Перфоратор пуст. Нужен чистый бланк.", "Teshgich boʻsh. Unga boʻsh karta kerak."),
("msg.c2_card_punched", "Clack. The card is punched.", "Щёлк. Бланк пробит.", "Chiq. Karta teshildi."),
("msg.c2_card_returned", "You slip the card back into the tray.", "Вы возвращаете бланк в лоток.", "Kartani tokchaga qaytardingiz."),
("msg.c2_no_pressure", "The tubes are dead: no pressure.", "Трубы мертвы: нет давления.", "Quvurlar jim: bosim yoʻq."),
("msg.c2_tube_empty", "The canister is empty.", "Капсула пуста.", "Kapsula boʻsh."),
("msg.c2_canister_loaded", "The card goes into the canister.", "Бланк отправляется в капсулу.", "Karta kapsulaga solindi."),
("msg.c2_notfound", "The canister returns with a red slip: FILE NOT FOUND.", "Капсула возвращается с красной запиской: ДЕЛО НЕ НАЙДЕНО.", "Kapsula qizil qogʻoz bilan qaytdi: ISH TOPILMADI."),
("msg.c2_nodest", "The canister thumps back. No one answered there.", "Капсула с глухим стуком возвращается. Там никто не ответил.", "Kapsula gup etib qaytdi. U yerda hech kim javob bermadi."),
("msg.c2_file", "The canister thumps back, heavier now.", "Капсула возвращается — теперь тяжелее.", "Kapsula qaytdi — endi ogʻirroq."),
("msg.c2_locker_locked", "Locked.", "Заперто.", "Qulflangan."),
("msg.c2_locker_open", "Locker 9 opens. Leyla's receiver hangs on a hook.", "Шкафчик 9 открыт. На крючке висит приёмник Лейлы.", "9-shkafcha ochildi. Ilgakda Leylaning qabul qilgichi osilib turibdi."),
("msg.c2_grille", "The grille swings open on two loose screws.", "Вентиляционная решётка открывается: два винта едва держатся.", "Shamollatish panjarasi ochildi: ikki vinti boʻshab qolgan ekan."),
("msg.c2_ledger", "The ledger is hollow.", "Гроссбух полый внутри.", "Hisob daftarining ichi kovak ekan."),
("msg.c2_hatch", "The hatch lifts with a groan.", "Люк со стоном поднимается.", "Lyuk gʻijirlab koʻtarildi."),
("msg.c2_garbled", "A shrill chatter: the speed is wrong.", "Визгливая трескотня: скорость не та.", "Chiyillagan shovqin: tezlik notoʻgʻri."),
("msg.c2_deck_empty", "There is no reel on the deck.", "На магнитофоне нет катушки.", "Magnitofonda gʻaltak yoʻq."),
("msg.c2_dial_wrong", "The dial whirs back. Nothing.", "Диск с жужжанием возвращается. Ничего.", "Disk gʻuvillab qaytdi. Hech narsa."),
("msg.c2_booth_open", "The booth door unlatches.", "Дверь кинобудки отщёлкивается.", "Kinobudka eshigi ochildi."),
("msg.c2_reel_repaired", "The splices hold. The reel is whole again.", "Склейки держат. Бобина снова цела.", "Yelimlar ushladi. Bobina yana butun."),
("msg.c2_splice_wrong", "All four strips are in, but the shadows jump from frame to frame. The order is wrong.", "Все четыре полоски вклеены, но тени скачут от кадра к кадру. Порядок неверный.", "Toʻrtala tasma ham yopishtirildi, lekin soyalar kadrdan kadrga sakraydi. Tartib notoʻgʻri."),
("msg.c2_projector_off", "The projector lamp goes dark.", "Лампа проектора гаснет.", "Proyektor chirogʻi oʻchdi."),
("msg.c2_projector_empty", "The lamp throws a blank white square onto the screen. There is no film in the gate.", "Лампа бросает на экран пустой белый квадрат. В проекторе нет плёнки.", "Chiroq ekranga boʻm-boʻsh oq toʻrtburchak tushirdi. Proyektorda lenta yoʻq."),
("msg.c2_blurred", "The picture is blurred.", "Изображение размыто.", "Tasvir xira."),
("msg.c2_recorded_sign", "The crystal flares. It keeps her sign now.", "Кристалл вспыхивает. Теперь в нём её знак.", "Billur chaqnadi. Endi unda uning belgisi saqlanadi."),
("msg.c2_recorded_mark", "The crystal flares. It keeps Strand's mark now.", "Кристалл вспыхивает. Теперь в нём знак Странда.", "Billur chaqnadi. Endi unda Strand belgisi saqlanadi."),
("msg.c2_lens_refused", "The lens already remembers Strand's mark.", "Линза уже помнит знак Странда.", "Linza Strand belgisini allaqachon eslab qolgan."),
("msg.c2_socket_full", "Something is already in the socket.", "В гнезде уже что-то есть.", "Uyachada allaqachon nimadir bor."),
("msg.c2_port_blank", "A blank crystal shows nothing.", "Чистый кристалл ничего не показывает.", "Boʻsh billur hech narsa koʻrsatmaydi."),
("msg.c2_vault_unlocked", "The images lock into the engraving. Bolts slide back, one after another.", "Изображения совпадают с гравировкой. Засовы отходят один за другим.", "Tasvirlar oʻyma bilan mos tushdi. Zulfinlar birin-ketin ochildi."),
("msg.c2_wheel_locked", "The wheel won't move: the bolts are still in.", "Штурвал не двигается: засовы ещё закрыты.", "Gʻildirak qimirlamaydi: zulfinlar hali yopiq."),
("msg.c2_slide_drawer", "Glass slides in velvet slots.", "Стеклянные слайды в бархатных гнёздах.", "Baxmal uyachalardagi shisha slaydlar."),
("msg.c2_echo_released", "The echo turns to the light and is gone.", "Эхо поворачивается к свету и исчезает.", "Aks-sado yorugʻlikka yuzlandi va gʻoyib boʻldi."),
("msg.c2_echo_count", "Kept echoes released: %d / 3", "Освобождено эхо: %d / 3", "Ozod qilingan aks-sadolar: %d / 3"),
("msg.c2_receiver", "Signal: %s", "Сигнал: %s", "Signal: %s"),
# ---------------------------------------------------------------- feedback for taps on scenery and locked mechanisms (3D QA pass)
("msg.c2_catalogue_drawers", "Drawers of staff index cards, 00 to 09.", "Ящики с карточками сотрудников, от 00 до 09.", "Xodimlar kartochkalari solingan tortmalar, 00 dan 09 gacha."),
("msg.c2_reading_table", "An open register under the banker's lamp, a magnifier and someone's spectacles.", "Раскрытый журнал под лампой, лупа и чьи-то очки.", "Chiroq ostida ochiq jurnal, lupa va kimningdir koʻzoynagi."),
("msg.c2_stacks_boxes", "Boxes of records, shelf after shelf, year after year.", "Коробки с документами, полка за полкой, год за годом.", "Hujjat qutilari: javon ketidan javon, yil ketidan yil."),
("msg.c2_chart_rule", "A hand-painted routing chart: a request card goes to the book.", "Схема маршрутов, расписанная от руки: бланк запроса отправляется к книге.", "Qoʻlda chizilgan yoʻnalishlar sxemasi: soʻrov kartasi kitobga yuboriladi."),
("msg.c2_slide_gate_empty", "The slide gate is empty.", "Рамка для слайда пуста.", "Slayd uyasi boʻsh."),
("msg.c2_screen_dark", "The screen is dark. Nothing is being projected.", "Экран тёмный. Ничего не проецируется.", "Ekran qorongʻi. Hech narsa koʻrsatilmayapti."),
("msg.c2_port_empty", "An empty crystal port. It wants a kept image.", "Пустое гнездо для кристалла. Ему нужен запечатлённый образ.", "Boʻsh billur uyachasi. Unga saqlangan tasvir kerak."),
("msg.c2_vault_shut", "Eight bolts hold the door. The glass disc above the wheel shows an engraving.", "Дверь держат восемь засовов. На стеклянном диске над штурвалом — гравировка.", "Eshikni sakkizta zulfin ushlab turibdi. Shturval ustidagi shisha diskda oʻyma naqsh bor."),
("msg.c2_disc", "Two images meet on the glass. They must match the engraving.", "На стекле сходятся два образа. Они должны совпасть с гравировкой.", "Shishada ikki tasvir uchrashadi. Ular oʻyma naqshga mos kelishi kerak."),
("msg.c2_locker_empty", "Locker 9. Nothing left inside.", "Шкафчик 9. Внутри больше ничего нет.", "9-shkafcha. Ichida boshqa hech narsa qolmagan."),
("msg.c2_dial_lock", "A rotary dial. Three digits open the latch.", "Дисковый номеронабиратель. Защёлку открывают три цифры.", "Diskli raqam tergich. Ilgakni uchta raqam ochadi."),
("msg.c2_socket_empty", "An empty crystal socket under the screen.", "Пустое гнездо для кристалла под экраном.", "Ekran ostida boʻsh billur uyachasi."),
("msg.c2_booth_locked", "Locked. A rotary dial is set into the door.", "Заперто. В дверь вделан дисковый номеронабиратель.", "Qulflangan. Eshikka diskli raqam tergich oʻrnatilgan."),
("msg.c2_splicer_box", "A light box for reading film strips.", "Световой стол для просмотра кадров плёнки.", "Lenta kadrlarini koʻrish uchun yorugʻlik stoli."),

# ---------------------------------------------------------------- captions (sound + story)
("cap2.compressor", "[The compressor coughs and hums]", "[Компрессор кашляет и гудит]", "[Kompressor yoʻtalib gʻuvillaydi]"),
("cap2.whoosh", "[A canister whooshes through the tubes]", "[По трубам со свистом летит капсула]", "[Quvurlardan kapsula shuvillab oʻtdi]"),
("cap2.static", "[Receiver static]", "[Помехи в приёмнике]", "[Qabul qilgich shovqini]"),
("cap2.clicks", "[Clicks: %s]", "[Щелчки: %s]", "[Chiqillashlar: %s]"),
("cap2.projector", "[The projector rattles]", "[Стрекочет проектор]", "[Proyektor shiqirlaydi]"),
("cap2.bolts", "[Bolts clank free]", "[Лязг освобождённых засовов]", "[Zulfinlar shaqillab ochildi]"),
("cap2.leyla_echo", "For a moment Leyla is there, in 1979. She touches a drawer of the slide cabinet and fades.", "На миг здесь Лейла — 1979 год. Она касается ящика со слайдами и тает.", "Bir lahza Leyla shu yerda — 1979-yil. U slaydlar javonining tortmasiga tegadi va yoʻqoladi."),
("cap2.lens_hum", "The crystal lens hums: something kept is near.", "Кристаллическая линза гудит: рядом что-то хранимое.", "Billur linza gʻuvillaydi: yaqinda saqlab qolingan nimadir bor."),
("intro2.1", "Beyond Laboratory 7, a corridor leads to Records Archive B.", "За Лабораторией 7 коридор ведёт в архив документов «Б».", "7-laboratoriya ortidagi yoʻlak «B» hujjatlar arxiviga olib boradi."),
("intro2.2", "Somewhere in here, Leyla left the rest of her trail.", "Где-то здесь Лейла оставила продолжение своего следа.", "Leyla izining davomini shu yerda bir joyda qoldirgan."),
("cap2.goal", "Leyla's staff badge is in your pocket. Her file must be somewhere in this archive.", "В кармане — пропуск Лейлы. Её личное дело должно быть где-то в этом архиве.", "Choʻntagingizda Leylaning guvohnomasi bor. Uning shaxsiy ishi shu arxivning bir joyida boʻlishi kerak."),
("doc2.file", "To whoever opens my file:\nI came back in 1996. The Institute is sealed, but the archive still breathes — the tubes, the lamps, the vault.\nI hid my voice where my receiver can hear it. Locker 9 keeps the receiver.\n— L.R.", "Тому, кто откроет моё дело:\nЯ вернулась в 1996-м. Институт запечатан, но архив ещё дышит — трубы, лампы, хранилище.\nЯ спрятала свой голос там, где его слышит мой приёмник. Приёмник — в шкафчике 9.\n— Л.Р.", "Shaxsiy ishimni ochgan kishiga:\n1996-yilda qaytib keldim. Institut muhrlangan, ammo arxiv hali nafas olyapti — quvurlar, chiroqlar, seyfxona.\nOvozimni qabul qilgichim eshita oladigan joyga yashirdim. Qabul qilgich 9-shkafchada.\n— L.R."),
("doc2.tape_1996", "1996. Day one. The Array still hums beneath the floor. I will record what I find and hide each reel where only my receiver can hear it.", "1996. День первый. Решётка всё ещё гудит под полом. Я буду записывать всё, что найду, и прятать каждую катушку там, где её слышит только мой приёмник.", "1996. Birinchi kun. Panjara hali ham pol ostida gʻuvillaydi. Topganlarimni yozib boraman va har bir gʻaltakni faqat qabul qilgichim eshitadigan joyga yashiraman."),
("doc2.tape_1997", "1997. The static speaks names. Forty-one names. Strand did not lose them. He kept them.", "1997. Помехи шепчут имена. Сорок одно имя. Странд их не потерял. Он их сохранил.", "1997. Shovqin ismlarni aytadi. Qirq bitta ism. Strand ularni yoʻqotmadi. U ularni saqlab qoldi."),
("doc2.tape_1998", "1998. My sign is sealed into the vault beside Strand's mark. My sign is on his old film. The booth answers to my reels, in the order I made them. If I do not come back, the way down is inside.", "1998. Мой знак запечатан в хранилище рядом со знаком Странда. Мой знак — на его старом фильме. Кинобудка отвечает моим катушкам — в том порядке, в каком я их записала. Если я не вернусь, путь вниз — внутри.", "1998. Belgim seyfxonaga Strand belgisi yoniga muhrlangan. Belgim uning eski filmida bor. Kinobudka gʻaltaklarimga ularni yozgan tartibimda javob beradi. Agar qaytmasam, pastga yoʻl ichkarida."),
("film.1", "Meridian Institute, 1979. The Array Hall.", "Институт «Меридиан», 1979. Зал Решётки.", "«Meridian» instituti, 1979. Panjara zali."),
("film.2", "Professor Strand demonstrates light memory.", "Профессор Странд демонстрирует световую память.", "Professor Strand yorugʻlik xotirasini namoyish etmoqda."),
("film.3", "Forty-one of us. The whole staff.", "Сорок один человек. Весь персонал.", "Qirq birtamiz. Barcha xodimlar."),
("film.4", "Dr. Rahimova draws her sign on the light glass.", "Д-р Рахимова рисует свой знак на световом стекле.", "Dr. Rahimova yorugʻlik oynasiga oʻz belgisini chizmoqda."),
("film.secret", "13 November 1979. Strand, alone: “If the Array keeps them, I will be with them. Forgive me, Leyla.”", "13 ноября 1979. Странд, один: «Если Решётка сохранит их, я буду с ними. Прости меня, Лейла».", "1979-yil 13-noyabr. Strand, yolgʻiz: «Agar Panjara ularni saqlab qolsa, men ular bilan boʻlaman. Meni kechir, Leyla»."),
("cap2.vault_reel", "The Array Hall. Forty-one silhouettes in the light. And a forty-second at the edge of the frame: Leyla, 1998.", "Зал Решётки. Сорок один силуэт в свете. И сорок второй на краю кадра: Лейла, 1998.", "Panjara zali. Yorugʻlikda qirq bitta siluet. Kadr chetida esa qirq ikkinchisi: Leyla, 1998."),
("echo2.catalogue", "An archivist files a card that no one will ever read.", "Архивистка ставит на место карточку, которую уже никто не прочтёт.", "Arxivchi ayol hech kim oʻqimaydigan kartochkani joyiga qoʻyadi."),
("echo2.stacks", "Two scientists argue in silence over an open ledger.", "Двое учёных беззвучно спорят над открытым гроссбухом.", "Ikki olim ochiq hisob daftari ustida jimgina bahslashmoqda."),
("echo2.booth", "Strand watches the screen through the booth window, smiling at someone you cannot see.", "Странд смотрит на экран через окно будки и улыбается кому-то, кого вы не видите.", "Strand budka oynasidan ekranga qarab, siz koʻrmaydigan kimgadir jilmayadi."),
# ---------------------------------------------------------------- finale + epilogue
("ui.choice_keys_prompt", "Two keys rest on the velvet. Lifting one will lock the other.", "На бархате лежат два ключа. Если поднять один, другой запрётся.", "Baxmalda ikki kalit yotibdi. Birini olsangiz, ikkinchisi qulflanadi."),
("ui.take_strand_key", "Strand's key", "Ключ Странда", "Strandning kaliti"),
("ui.take_leyla_key", "Leyla's key", "Ключ Лейлы", "Leylaning kaliti"),
("ui.echoes", "Kept echoes", "Сохранённое эхо", "Saqlangan aks-sadolar"),
("epi2.42nd", "She went in after them.", "Она ушла за ними.", "U ularning ortidan ketgan."),
("epi2.strand_key", "You take Strand's key. Somewhere below, the Array Hall waits.", "Вы берёте ключ Странда. Где-то внизу ждёт Зал Решётки.", "Strandning kalitini oldingiz. Pastda qayerdadir Panjara zali kutmoqda."),
("epi2.leyla_key", "You take Leyla's key. Her way down leads through the crystal vaults.", "Вы берёте ключ Лейлы. Её путь вниз ведёт через хранилища кристаллов.", "Leylaning kalitini oldingiz. Uning pastga yoʻli billur omborlari orqali oʻtadi."),
("epi2.echoes", "Three kept echoes walk free tonight.", "Этой ночью три сохранённых эха обрели свободу.", "Bu tun uchta saqlangan aks-sado ozod boʻldi."),
("epi2.recorder", "Somewhere below, a recorder clicks on.", "Где-то внизу щёлкает и включается магнитофон.", "Pastda qayerdadir magnitofon chiq etib yoqildi."),
("achv.echoes_of_the_archive", "Echoes of the Archive", "Эхо архива", "Arxiv aks-sadolari"),
# ---------------------------------------------------------------- engagement pass (docs/ENGAGEMENT.md): reveals, secret, cliffhanger
("cap2.reel_41", "The Array Hall, 1979. Forty-one silhouettes in the light.", "Зал Решётки, 1979. Сорок один силуэт в свете.", "Panjara zali, 1979. Yorugʻlikda qirq bitta siluet."),
("cap2.reel_42", "And a forty-second, at the edge of the frame. Leyla, 1998.", "И сорок второй — на краю кадра. Лейла, 1998.", "Kadr chetida esa qirq ikkinchisi. Leyla, 1998."),
("cap2.vault_answers", "[Across the hall, the vault door answers with a dull clunk]", "[Через зал дверь хранилища отвечает глухим лязгом]", "[Zalning narigi tomonida seyfxona eshigi boʻgʻiq taqillab javob berdi]"),
("cap2.whisper", "[Under the static, a voice counts, very far away: …forty… forty-one… forty-two]", "[Сквозь помехи, очень далеко, чей-то голос считает: …сорок… сорок один… сорок два]", "[Shovqin ostida, juda uzoqda, kimdir sanayapti: …qirq… qirq bir… qirq ikki]"),
("achv.forty_two", "Forty-Two", "Сорок два", "Qirq ikki"),
("cap2.rumble", "[Under the floor, something old and heavy wakes: a lift motor]", "[Под полом просыпается что-то старое и тяжёлое: мотор лифта]", "[Pol ostida eski va ogʻir bir narsa uygʻondi: lift motori]"),
("cap2.shaft_lamps", "[Floor by floor, the lamps of the lift shaft wake]", "[Этаж за этажом просыпаются лампы шахты лифта]", "[Qavatma-qavat lift shaxtasining chiroqlari uygʻonmoqda]"),
("cap2.shaft_hum", "[Far below: the hum of the transformer halls]", "[Глубоко внизу гудят трансформаторные залы]", "[Juda pastda transformator zallari gʻuvillaydi]"),
("tease2.voice_1", "“If you hear this, the lift still works.”", "«Если ты это слышишь, лифт ещё работает».", "«Agar buni eshitayotgan boʻlsang, lift hali ishlaydi»."),
("tease2.voice_2", "“The Choir and the Nursery must sing together, or the Array stays deaf.”", "«Хор и Питомник должны петь вместе, иначе Решётка останется глухой».", "«Xor va Koʻchatxona birga kuylashi kerak, aks holda Panjara kar boʻlib qoladi»."),
("tease2.voice_3", "“I am going down to them.”", "«Я спускаюсь к ним».", "«Men ularning oldiga tushyapman»."),
("tease2.voice_who", "Leyla Rahimova · a recorder on Level −2 · 1998", "Лейла Рахимова · магнитофон на уровне −2 · 1998", "Leyla Rahimova · −2-qavatdagi magnitofon · 1998"),
("tease2.second_cap", "[Under the hiss, a second voice. An old man's. Very close.]", "[Сквозь шипение — второй голос. Старческий. Совсем близко.]", "[Shitirlash ostida ikkinchi ovoz. Keksa kishiniki. Juda yaqinda.]"),
("tease2.second_voice", "“Leyla?… Who is that with you?”", "«Лейла?… Кто это с тобой?»", "«Leyla?… Yoningdagi kim?»"),
("tease2.tag_strand_key", "Strand's key opens the Choir Hall: the transformers, the singing tubes, and the office where he kept his last secret.", "Ключ Странда открывает Зал Хора: трансформаторы, поющие трубы и кабинет, где он хранил свою последнюю тайну.", "Strandning kaliti Xor zalini ochadi: transformatorlar, kuylovchi quvurlar va u soʻnggi sirini saqlagan xona."),
("tease2.tag_leyla_key", "Leyla's key opens the Nursery: the crystal vaults, her last camp, and a recorder that is still turning.", "Ключ Лейлы открывает Питомник: хранилища кристаллов, её последний лагерь и магнитофон, который всё ещё крутится.", "Leylaning kaliti Koʻchatxonani ochadi: billur omborlari, uning soʻnggi qarorgohi va hamon aylanayotgan magnitofon."),
("tease2.coming_soon", "Chapters 3 and 4 are on their way. Your key and your choices are saved for them.", "Главы 3 и 4 уже в пути. Ваш ключ и ваши решения сохранены для них.", "3- va 4-boblar yoʻlda. Kalitingiz va tanlovlaringiz ular uchun saqlangan."),
("tease2.unlock_line", "Chapters 3 and 4 finish the story. One purchase unlocks both; no ads, ever.", "Главы 3 и 4 завершают историю. Одна покупка открывает обе; никакой рекламы.", "3- va 4-boblar hikoyani yakunlaydi. Bitta xarid ikkalasini ochadi; hech qanday reklama yoʻq."),
("tease2.continue_story", "Continue the story", "Продолжить историю", "Hikoyani davom ettirish"),
("tease2.not_now", "Not now", "Не сейчас", "Hozir emas"),
]

H = {
"c2_catalogue": [
    ("Leyla's badge carries a number. The card catalogue stands on the west wall, past the stacks.", "На пропуске Лейлы есть номер. Картотека стоит у западной стены, за стеллажами.", "Leylaning guvohnomasida raqam bor. Kartoteka gʻarbiy devor yonida, javonlar ortida."),
    ("The catalogue drawers are numbered by the first two digits.", "Ящики картотеки пронумерованы по первым двум цифрам.", "Kartoteka tortmalari dastlabki ikki raqam boʻyicha raqamlangan."),
    ("Drawer 04, divider 1–, card 17.", "Ящик 04, разделитель 1–, карточка 17.", "04-tortma, 1– ajratgich, 17-kartochka."),
],
"c2_compressor": [
    ("The tube station is dead: there is no pressure. The tube compressor makes it.", "Станция пневмопочты не работает: нет давления. Его создаёт компрессор.", "Pnevmatik pochta ishlamayapti: bosim yoʻq. Bosimni kompressor beradi."),
    ("The compressor's plate shows which valve feeds which gauge. Both needles need their green marks.", "Табличка на компрессоре показывает, какой вентиль питает какой манометр. Обе стрелки должны встать на зелёные метки.", "Kompressor lavhasida qaysi ventil qaysi manometrga ulangani koʻrsatilgan. Ikkala mil ham yashil belgiga kelishi kerak."),
    ("Valves: A %d, B %d, C %d.", "Вентили: A %d, B %d, C %d.", "Ventillar: A %d, B %d, C %d."),
],
"c2_punch": [
    ("The stacks only answer punched requests.", "Хранилище отвечает только на пробитые запросы.", "Fond faqat teshilgan soʻrovlarga javob beradi."),
    ("Take a blank card from the station tray and copy the index card's notches with the punch.", "Возьмите чистый бланк из лотка станции и перенесите вырезы с карточки на перфоратор.", "Stansiya tokchasidan boʻsh karta oling va kartochkadagi kesiklarni teshgichda takrorlang."),
    ("Press keys %s (%s), then pull the lever.", "Нажмите клавиши %s (%s), затем рычаг.", "%s-tugmalarni bosing (%s), soʻng dastakni torting."),
],
"c2_dispatch": [
    ("Requests travel by tube.", "Запросы путешествуют по трубам.", "Soʻrovlar quvur orqali yuboriladi."),
    ("The chart on the wall shows where request cards go.", "Схема на стене показывает, куда отправлять бланки.", "Devordagi sxema soʻrov kartalari qayerga ketishini koʻrsatadi."),
    ("Card in the canister, dial on the book, pull the lever.", "Бланк в капсулу, диск на книгу, потяните рычаг.", "Kartani kapsulaga soling, diskni kitobga qoʻying, dastakni torting."),
],
"c2_take_file": [
    ("The canister came back.", "Капсула вернулась.", "Kapsula qaytib keldi."),
    ("Open the receive tray of the tube station.", "Откройте приёмный лоток станции.", "Stansiyaning qabul tokchasini oching."),
    ("Take Leyla's file and the key from the canister.", "Возьмите из капсулы дело Лейлы и ключ.", "Kapsuladan Leylaning ishini va kalitni oling."),
],
"c2_locker": [
    ("Leyla's letter names a locker.", "В письме Лейлы назван шкафчик.", "Leyla maktubida shkafcha tilga olingan."),
    ("Her file held a small key with a tag.", "В её деле был маленький ключ с биркой.", "Uning ishida yorliqli kichik kalit bor edi."),
    ("Use the locker key on locker 9.", "Используйте ключ на шкафчике 9.", "Kalitni 9-shkafchada ishlating."),
],
"c2_take_receiver": [
    ("Locker 9 is open.", "Шкафчик 9 открыт.", "9-shkafcha ochiq."),
    ("Something hangs on its hook.", "На крючке что-то висит.", "Ilgakda nimadir osilib turibdi."),
    ("Take the pocket receiver.", "Возьмите карманный приёмник.", "Choʻntak qabul qilgichini oling."),
],
"c2_hunt": [
    ("Leyla hid her voice where her receiver can hear it.", "Лейла спрятала свой голос там, где его слышит приёмник.", "Leyla ovozini qabul qilgich eshitadigan joyga yashirgan."),
    ("Select the receiver and watch its needle as you look around.", "Выберите приёмник и следите за стрелкой, осматриваясь.", "Qabul qilgichni tanlang va atrofga qaraganda milini kuzating."),
    ("Vent grille on the west wall, hollow ledger in the stacks, floor hatch near the reading table.", "Вентиляционная решётка на западной стене, полый гроссбух на стеллаже, люк у читального стола.", "Gʻarbiy devordagi shamollatish panjarasi, javondagi kovak hisob daftari, mutolaa stoli yonidagi lyuk."),
],
"c2_tape": [
    ("The reels need a player.", "Катушкам нужен магнитофон.", "Gʻaltaklarga magnitofon kerak."),
    ("The archivist's deck plays them. Match the speed written on the reels.", "Их проигрывает магнитофон архивариуса. Выставьте скорость, указанную на катушках.", "Ularni arxivchining magnitofoni qoʻyadi. Gʻaltakda yozilgan tezlikni tanlang."),
    ("Speed 4.75, a reel on the deck, press Play. Do it for all three.", "Скорость 4.75, катушку на магнитофон, нажмите «Пуск». Для всех трёх.", "Tezlik 4.75, gʻaltakni magnitofonga qoʻying, ijro tugmasini bosing. Uchalasi uchun."),
],
"c2_booth": [
    ("The booth door has a dial.", "На двери кинобудки есть диск.", "Kinobudka eshigida disk bor."),
    ("“The booth answers to my reels, in the order I made them.” Count each reel's clicks.", "«Кинобудка отвечает моим катушкам — в том порядке, в каком я их записала». Сосчитайте щелчки.", "«Kinobudka gʻaltaklarimga ularni yozgan tartibimda javob beradi». Chiqillashlarni sanang."),
    ("Dial %d, %d, %d.", "Наберите %d, %d, %d.", "%d, %d, %d ni tering."),
],
"c2_splice": [
    ("The film is in pieces. Put it together on the film splicer in the booth.", "Плёнка разорвана на кусочки. Соберите её на склеечном прессе в кинобудке.", "Lenta boʻlaklarga boʻlingan. Uni kinobudkadagi yelimlagichda yigʻing."),
    ("The can's lid shows the day running from dawn to noon. Shadows shorten.", "На крышке коробки день идёт от рассвета к полудню. Тени укорачиваются.", "Quti qopqogʻida kun tongdan tushgacha davom etadi. Soyalar qisqaradi."),
    ("Order the frames from the longest shadow to the shortest.", "Расположите кадры от самой длинной тени к самой короткой.", "Kadrlarni eng uzun soyadan eng qisqasigacha joylang."),
],
"c2_take_reel": [
    ("The reel is whole again.", "Бобина снова цела.", "Bobina yana butun."),
    ("It is still on the splicer.", "Она ещё на склеечном прессе.", "U hali yelimlagichda."),
    ("Take the film reel.", "Возьмите бобину.", "Bobinani oling."),
],
"c2_project": [
    ("Strand's film wants a projector.", "Фильму Странда нужен проектор.", "Strandning filmiga proyektor kerak."),
    ("Thread the reel and pull the run lever.", "Заправьте плёнку и потяните рычаг пуска.", "Lentani oʻrnating va ishga tushirish dastagini torting."),
    ("Use the reel on the projector, then pull the lever.", "Используйте бобину на проекторе, затем рычаг.", "Bobinani proyektorda ishlating, soʻng dastakni torting."),
],
"c2_take_crystal": [
    ("The booth keeps something for the light.", "В кинобудке есть кое-что для света.", "Kinobudkada yorugʻlik uchun nimadir bor."),
    ("A velvet case lies on the shelf.", "На полке лежит бархатный футляр.", "Tokchada baxmal quti yotibdi."),
    ("Take a blank crystal from the lens case.", "Возьмите чистый кристалл из футляра.", "Qutidan boʻsh billur oling."),
],
"c2_focus": [
    ("The picture on the screen is blurred.", "Изображение на экране размыто.", "Ekrandagi tasvir xira."),
    ("Turn the projector's focus ring.", "Поверните кольцо фокуса проектора.", "Proyektorning fokus halqasini buring."),
    ("Turn the focus ring to mark %d.", "Поверните кольцо фокуса на метку %d.", "Fokus halqasini %d-belgiga buring."),
],
"c2_record_sign": [
    ("“The crystal remembers what falls on it.”", "«Кристалл помнит то, что на него падает».", "«Billur ustiga tushgan narsani eslab qoladi»."),
    ("The screen frame has a socket for a crystal. Show only her sign, sharp.", "На раме экрана есть гнездо для кристалла. Покажите только её знак, чётко.", "Ekran romida billur uchun uyacha bor. Faqat uning belgisini aniq koʻrsating."),
    ("Hold the last frame in focus and seat a blank crystal in the screen socket.", "Остановитесь на последнем кадре в фокусе и вставьте чистый кристалл в гнездо экрана.", "Oxirgi kadrni aniq holda toʻxtating va boʻsh billurni ekran uyachasiga qoʻying."),
],
"c2_mark": [
    ("Leyla's echo pointed somewhere.", "Эхо Лейлы на что-то указало.", "Leylaning aks-sadosi nimanidir koʻrsatdi."),
    ("The slide cabinet, the drawer with the star. Use the slide projector with the film projector off.", "Шкаф для слайдов, ящик со звездой. Диапроектор — при выключенном кинопроекторе.", "Slaydlar javoni, yulduzli tortma. Kinoproyektor oʻchiq holda diaproyektordan foydalaning."),
    ("Emblem slide in the slide projector, meridian upright, film lamp off, blank crystal in the socket.", "Слайд в диапроектор, меридиан вертикально, лампа кинопроектора выключена, чистый кристалл в гнездо.", "Slaydni diaproyektorga, meridianni tik, kinoproyektor chirogʻini oʻchiring, boʻsh billurni uyachaga."),
],
"c2_ports": [
    ("The vault door has two lenses.", "На двери хранилища две линзы.", "Seyfxona eshigida ikkita linza bor."),
    ("The plates show which mark goes where: the star on the left, the crescent on the right.", "Таблички показывают, где какой знак: звезда слева, полумесяц справа.", "Lavhalar qaysi belgi qayerga ekanini koʻrsatadi: yulduz chapda, yarim oy oʻngda."),
    ("Strand's mark crystal in the left port, Leyla's sign crystal in the right.", "Кристалл со знаком Странда — в левый порт, со знаком Лейлы — в правый.", "Strand belgili billur chap portga, Leyla belgili billur oʻng portga."),
],
"c2_align": [
    ("Match the faint engraving on the glass.", "Совместите изображения с бледной гравировкой на стекле.", "Tasvirlarni shishadagi xira oʻyma bilan moslang."),
    ("The mark stands upright. The sign inside the ring is turned and smaller: copy the engraving exactly.", "Знак стоит вертикально. Полумесяц внутри кольца повёрнут и меньше: повторите гравировку точно.", "Belgi tik turadi. Halqa ichidagi yarim oy burilgan va kichikroq: oʻymani aynan takrorlang."),
    ("Left collar upright, right collar to mark %d, zoom to mark %d.", "Левое кольцо вертикально, правое — на отметку %d, масштаб — на отметку %d.", "Chap halqa tik, oʻng halqa %d-belgiga, kattalik %d-belgiga."),
],
"c2_wheel": [
    ("The bolts are free.", "Засовы свободны.", "Zulfinlar boʻshadi."),
    ("Turn the vault wheel.", "Поверните штурвал хранилища.", "Seyfxona gʻildiragini buring."),
    ("Tap the wheel three times.", "Нажмите на штурвал три раза.", "Gʻildirakka uch marta bosing."),
],
"c2_finale": [
    ("Two keys. You may take only one.", "Два ключа. Взять можно только один.", "Ikki kalit. Faqat bittasini olish mumkin."),
    ("Strand's key opens the Array Hall. Leyla's opens the crystal vaults.", "Ключ Странда открывает Зал Решётки, ключ Лейлы — хранилища кристаллов.", "Strandning kaliti Panjara zalini, Leylaniki billur omborlarini ochadi."),
    ("Choose.", "Выбирайте.", "Tanlang."),
],
}
