# -*- coding: utf-8 -*-
"""Chapter 1 strings: items, documents, objects, feedback messages, captions, hints. (key, en, ru, uz)"""

S = [
# ---------------------------------------------------------------- items
("item.notebook.name", "Leyla's notebook", "Блокнот Лейлы", "Leylaning daftari"),
("item.notebook.desc", "A lab journal in Leyla Rahimova's handwriting. One page looks oddly blank.", "Лабораторный журнал, исписанный рукой Лейлы Рахимовой. Одна страница странно пуста.", "Leyla Rahimovaning qoʻli bilan yozilgan laboratoriya jurnali. Bir sahifasi negadir boʻm-boʻsh."),
("item.uv_lamp_empty.name", "UV lamp (empty)", "УФ-лампа (пустая)", "UB chiroq (boʻsh)"),
("item.uv_lamp_empty.desc", "A lamp with a violet lens. Its battery bay is empty.", "Лампа с фиолетовым стеклом. Отсек для батареи пуст.", "Binafsha shishali chiroq. Batareya joyi boʻsh."),
("item.battery_cell.name", "Battery cell", "Батарея", "Batareya"),
("item.battery_cell.desc", "A heavy old cell. Surprisingly, it still holds a charge.", "Тяжёлая старая батарея. Как ни странно, ещё держит заряд.", "Ogʻir eski batareya. Hayratlanarlisi, hali ham quvvati bor."),
("item.uv_lamp.name", "UV lamp", "УФ-лампа", "UB chiroq"),
("item.uv_lamp.desc", "Shines ultraviolet light. Invisible ink glows under it. Select it, then drag across surfaces.", "Светит ультрафиолетом — невидимые чернила начинают светиться. Выберите её и ведите по поверхностям.", "Ultrabinafsha nur sochadi — koʻrinmas siyoh yorishadi. Uni tanlang va yuzalar boʻylab suring."),
("item.brass_key.name", "Brass key", "Латунный ключ", "Jez kalit"),
("item.brass_key.desc", "A small ornate key. Too small for any door.", "Маленький резной ключ. Слишком мал для двери.", "Kichkina naqshli kalit. Eshik uchun juda kichik."),
("item.crystal_lens.name", "Crystal lens", "Кристаллическая линза", "Billur linza"),
("item.crystal_lens.desc", "A flawless crystal in a brass ring, faintly warm. The Lumen crystal remembers the light that falls on it.", "Безупречный кристалл в латунной оправе, едва тёплый. Кристалл Люмена помнит свет, который на него падает.", "Jez halqadagi benuqson billur, biroz iliq. Lumen billuri ustiga tushgan yorugʻlikni eslab qoladi."),
("item.crystal_lens.desc_recorded", "The crystal glows softly from within: it holds the Institute's mark.", "Кристалл мягко светится изнутри: в нём хранится знак института.", "Billur ichidan mayin yogʻdu sochadi: unda institut belgisi saqlangan."),
("item.strand_letter.name", "Strand's letter", "Письмо Странда", "Strandning maktubi"),
("item.strand_letter.desc", "Sealed with red wax and addressed to Leyla.", "Запечатано красным сургучом, адресовано Лейле.", "Qizil surgʻuch bilan muhrlangan, Leylaga atalgan."),
("item.radio_valve.name", "Radio valve", "Радиолампа", "Radiolampa"),
("item.radio_valve.desc", "A glass vacuum tube for an old valve radio.", "Стеклянная электронная лампа для старого радиоприёмника.", "Eski radiopriyomnik uchun shisha elektron lampa."),
("item.breaker_handle.name", "Breaker handle", "Рукоять рубильника", "Uzgich dastasi"),
("item.breaker_handle.desc", "A bakelite handle torn from a main breaker.", "Бакелитовая рукоять, снятая с главного рубильника.", "Asosiy uzgichdan yechib olingan bakelit dasta."),
("item.leyla_photo.name", "Photograph", "Фотография", "Surat"),
("item.leyla_photo.desc", "Leyla in Laboratory 7. Something is written on the back.", "Лейла в Лаборатории 7. На обороте что-то написано.", "Leyla 7-laboratoriyada. Orqasida nimadir yozilgan."),
("item.mirror_item.name", "Round mirror", "Круглое зеркало", "Dumaloq koʻzgu"),
("item.mirror_item.desc", "A brass-framed mirror with a mounting pin. It fits a mirror stand.", "Зеркало в латунной оправе со штифтом. Подходит к зеркальной стойке.", "Orqasida oʻrnatish qoziqchasi boʻlgan jez gardishli koʻzgu. Koʻzgu tirgagiga mos keladi."),

# ---------------------------------------------------------------- documents
("doc.notebook.p1", "12 November 1979\n\nStrand wants full resonance on Thursday. The crystal readings are wrong.\n\nIt is not replaying the light.\nIt is keeping it.", "12 ноября 1979\n\nСтранд хочет полный резонанс в четверг. Показания кристалла неверны.\n\nОн не воспроизводит свет.\nОн его удерживает.", "1979-yil 12-noyabr\n\nStrand payshanba kuni toʻliq rezonans istaydi. Billur koʻrsatkichlari notoʻgʻri.\n\nU yorugʻlikni takrorlamayapti.\nU uni ushlab qolyapti."),
("doc.notebook.p2", "14 November 1979, night\n\nEvery clock in the building stopped at the same moment.\n\nI set the lock of my desk drawer to that moment, so that I will never forget it.", "14 ноября 1979, ночь\n\nВсе часы в здании остановились в одно и то же мгновение.\n\nЯ установила замок ящика стола на это мгновение, чтобы никогда его не забыть.", "1979-yil 14-noyabr, tun\n\nBinodagi barcha soatlar bir lahzada toʻxtadi.\n\nOʻsha lahzani hech qachon unutmaslik uchun stol tortmamning qulfini shu lahzaga oʻrnatdim."),
("doc.notebook.p3", "Strand gave each of us one of his gear boxes.\n“Turn one wheel and its neighbour follows — like people,” he said.\n\nI keep the cell for my lamp inside mine.", "Странд подарил каждому из нас одну из своих шкатулок с шестернями.\n«Поверни одно колесо — и сосед последует за ним, как люди», — сказал он.\n\nВ своей я храню батарею для лампы.", "Strand har birimizga oʻzining tishli gʻildirakli qutichalaridan bittasini sovgʻa qilgan.\n«Bitta gʻildirakni bursang, qoʻshnisi ham ergashadi — xuddi odamlardek», degandi u.\n\nMen oʻzimnikida chirogʻim batareyasini saqlayman."),
("doc.notebook.p4", "Panel 7.\nLOCK, LIGHT and ARRAY must be live.\nThe VENT line must stay dead — or the dust from the Array Hall will reach us.", "Щит 7.\nЗАМОК, СВЕТ и РЕШЁТКА должны быть под током.\nЛиния ВЕНТИЛЯЦИИ должна оставаться обесточенной — иначе пыль из Зала Решётки дойдёт до нас.", "7-panel.\nQULF, YORUGʻLIK va PANJARA tok ostida boʻlishi kerak.\nSHAMOLLATISH liniyasi oʻchiq qolsin — aks holda Panjara zalidagi chang bizgacha yetib keladi."),
("doc.notebook.p5", "", "", ""),
("doc.notebook.p5_uv", "The safe answers in Strand's symbols:", "Сейф отвечает символами Странда:", "Seyf Strandning belgilari bilan javob beradi:"),
("doc.notebook.p6", "I took the handle of the main breaker and hid it where only my lamp can show the way.", "Я сняла рукоять главного рубильника и спрятала её там, куда дорогу укажет только моя лампа.", "Asosiy uzgichning dastasini yechib oldim va uni faqat chirogʻim yoʻl koʻrsata oladigan joyga yashirdim."),
("doc.notebook.p7", "Strand's beacon still calls on his old band — three numbers, over and over.\n\nMy encyclopedia remembers them.", "Маяк Странда всё ещё зовёт на его старой волне — три числа, снова и снова.\n\nМоя энциклопедия их помнит.", "Strandning mayogʻi hali ham oʻsha eski toʻlqinda chaqiryapti — uchta son, qayta-qayta.\n\nMening ensiklopediyam ularni eslaydi."),
("doc.notebook.p8", "If someone reads this: the Array must wake once more to open the door.\n\nThe door's eye opens only for the Institute's mark carried in Lumen light.\n\nTune it exactly as Strand wrote — or it will keep you too.", "Если кто-то читает это: Решётка должна проснуться ещё раз, чтобы открыть дверь.\n\nГлаз двери открывается только для знака института, принесённого светом Люмена.\n\nНастрой её точно так, как писал Странд, — иначе она удержит и тебя.", "Agar buni kimdir oʻqiyotgan boʻlsa: eshikni ochish uchun Panjara yana bir bor uygʻonishi kerak.\n\nEshik koʻzi faqat Lumen nuri olib kelgan institut belgisiga ochiladi.\n\nUni Strand yozganidek aniq sozla — aks holda u seni ham ushlab qoladi."),
("doc.letter", "Leyla —\n\nThe light opens any door when the three rings sing with the three samples, the heaviest first.\n\nDo not be afraid of it.\n\n— E. S.", "Лейла —\n\nСвет откроет любую дверь, когда три кольца запоют в лад с тремя образцами — начиная с самого тяжёлого.\n\nНе бойся его.\n\n— Э. С.", "Leyla —\n\nUch halqa uch namuna bilan hamohang kuylaganda — eng ogʻiridan boshlab — yorugʻlik har qanday eshikni ochadi.\n\nUndan qoʻrqma.\n\n— E. S."),
("doc.photo", "Lab 7, spring 1977.\nFor Mira — so she remembers my face.", "Лаб. 7, весна 1977.\nДля Миры — чтобы она помнила моё лицо.", "7-lab., 1977-yil bahori.\nMira uchun — yuzimni eslab qolsin."),
("doc.darkroom_note", "Only light and shadow may draw the Institute's mark.\nThe crystal remembers what falls on it.", "Знак института могут нарисовать только свет и тень.\nКристалл помнит то, что на него падает.", "Institut belgisini faqat yorugʻlik va soya chiza oladi.\nBillur ustiga tushgan narsani eslab qoladi."),
("doc.evidence", "Forty-one photographs. Forty-one names.\nA clipping, 1979: “Institute closed after ventilation accident.”\nA clipping, 1998: “Former researcher seen at the sealed Institute.”", "Сорок одна фотография. Сорок одно имя.\nВырезка, 1979: «Институт закрыт после аварии вентиляции».\nВырезка, 1998: «Бывшую сотрудницу видели у закрытого института».", "Qirq bitta surat. Qirq bitta ism.\nGazeta qirqimi, 1979: «Shamollatish avariyasidan soʻng institut yopildi».\nGazeta qirqimi, 1998: «Sobiq xodima yopiq institut yonida koʻrilgan»."),

# ---------------------------------------------------------------- objects (focus captions)
("obj.door", "Laboratory door — sealed by a magnetic lock", "Дверь лаборатории — заперта магнитным замком", "Laboratoriya eshigi — magnit qulf bilan yopilgan"),
("obj.door_open", "Laboratory door — open", "Дверь лаборатории — открыта", "Laboratoriya eshigi — ochiq"),
("obj.desk", "Leyla's desk", "Стол Лейлы", "Leylaning stoli"),
("obj.drawer", "Drawer lock — four brass wheels", "Замок ящика — четыре латунных колеса", "Tortma qulfi — toʻrtta jez gʻildirak"),
("obj.clock", "A flip clock, stopped", "Перекидные часы — остановились", "Varaqli soat — toʻxtab qolgan"),
("obj.gearbox", "Strand's gear box", "Шкатулка Странда с шестернями", "Strandning tishli gʻildirakli qutichasi"),
("obj.safe", "Wall safe", "Стенной сейф", "Devor seyfi"),
("obj.panel", "Panel 7", "Щит 7", "7-panel"),
("obj.radio", "Valve radio", "Ламповый радиоприёмник", "Lampali radiopriyomnik"),
("obj.projector", "Lumen projector", "Проектор «Люмен»", "«Lumen» proyektori"),
("obj.poster", "Tabula Resonantiarum — Strand's table of resonances", "Tabula Resonantiarum — таблица резонансов Странда", "Tabula Resonantiarum — Strandning rezonanslar jadvali"),
("obj.chalkboard", "Strand's chalkboard", "Доска Странда", "Strandning doskasi"),
("obj.bench", "Laboratory bench", "Лабораторный стол", "Laboratoriya stoli"),
("obj.vials", "Three samples, labelled only by density (ρ)", "Три образца, подписаны только плотностью (ρ)", "Uchta namuna — faqat zichligi (ρ) yozilgan"),
("obj.bookshelf", "Bookcase — a nine-volume encyclopedia", "Книжный шкаф — энциклопедия в девяти томах", "Kitob javoni — toʻqqiz jildli ensiklopediya"),
("obj.bookshelf_open", "Behind the bookcase: Leyla's darkroom", "За книжным шкафом — тёмная комната Лейлы", "Kitob javoni ortida — Leylaning qorongʻi xonasi"),
("obj.mirror_a", "Mirror stand", "Зеркальная стойка", "Koʻzgu tirgagi"),
("obj.mirror_b", "Mirror stand — the bracket is empty", "Зеркальная стойка — держатель пуст", "Koʻzgu tirgagi — ushlagich boʻsh"),
("obj.lock", "The door's eye — a light lock", "Глаз двери — световой замок", "Eshik koʻzi — yorugʻlik qulfi"),
("obj.window", "Barred window. The valley sleeps under the moon.", "Окно с решёткой. Долина спит под луной.", "Panjarali deraza. Vodiy oy ostida uxlayapti."),
("obj.coat", "A coat, still on its hook", "Пальто, всё ещё на вешалке", "Ilgichda hamon osilgan palto"),
("obj.drawing", "A child's drawing: the Institute, the sun, a woman in a white coat", "Детский рисунок: институт, солнце, женщина в белом халате", "Bola chizgan rasm: institut, quyosh, oq xalatli ayol"),
("obj.darkroom", "Leyla's darkroom", "Тёмная комната Лейлы", "Leylaning qorongʻi xonasi"),
("obj.evidence", "Leyla's evidence wall", "Стена улик Лейлы", "Leylaning dalillar devori"),
("obj.shadow", "Shadow sculpture — a brass ring and a rod", "Теневая скульптура — латунное кольцо и стержень", "Soya haykalchasi — jez halqa va sterjen"),
("obj.emblem", "The Institute's mark, with a socket at its heart", "Знак института с гнездом в центре", "Markazida uyachasi bor institut belgisi"),
("obj.cabinet", "A small locked cabinet", "Маленький запертый шкафчик", "Kichik qulflangan javoncha"),
("obj.cabinet_open", "A small cabinet, now unlocked", "Маленький шкафчик — теперь открыт", "Kichik javoncha — endi ochiq"),
("obj.filing", "Filing cabinet — staff records, mostly empty", "Картотека — личные дела, почти пустая", "Kartoteka — xodimlar hujjatlari, deyarli boʻsh"),
("obj.radiator", "A cold cast-iron radiator", "Холодный чугунный радиатор", "Sovuq choʻyan radiator"),

# ---------------------------------------------------------------- feedback messages
("msg.nothing", "Nothing happens.", "Ничего не происходит.", "Hech narsa boʻlmadi."),
("msg.door_sealed", "Sealed. The magnetic lock hums; its lamp glows red.", "Заперто. Магнитный замок гудит, его лампа горит красным.", "Yopiq. Magnit qulf gʻuvillaydi, chirogʻi qizil yonmoqda."),
("msg.drawer_locked", "Locked. Four brass wheels hold it shut.", "Заперто. Его держат четыре латунных колеса.", "Qulflangan. Uni toʻrtta jez gʻildirak ushlab turibdi."),
("msg.drawer_opened", "Click — the drawer slides open.", "Щелчок — ящик выдвигается.", "Chiq — tortma ochildi."),
("msg.box_opened", "The gears align and the lid springs open.", "Шестерни совпали, и крышка откидывается.", "Tishli gʻildiraklar mos keldi va qopqoq ochilib ketdi."),
("msg.combine_failed", "These don't fit together.", "Это не подходит друг к другу.", "Bular bir-biriga mos kelmaydi."),
("msg.lamp_ready", "The UV lamp flickers to life.", "УФ-лампа оживает.", "UB chiroq yonib ketdi."),
("msg.uv_page", "Hidden ink blooms on the blank page!", "На пустой странице проступают невидимые чернила!", "Boʻsh sahifada yashirin siyoh paydo boʻldi!"),
("msg.uv_desk", "A glowing mark appears on the side of the desk.", "На боковине стола проступает светящийся знак.", "Stolning yon tomonida yorugʻ belgi paydo boʻldi."),
("msg.safe_denied", "Wrong code. The safe buzzes.", "Неверный код. Сейф гудит.", "Kod notoʻgʻri. Seyf gʻuvillaydi."),
("msg.safe_opened", "The bolts slide back. The safe is open.", "Засовы отходят. Сейф открыт.", "Zulfinlar surildi. Seyf ochildi."),
("msg.keyhole", "The rosette sinks in; a panel slides away, revealing a keyhole.", "Розетка утапливается, панель сдвигается — под ней замочная скважина.", "Gul naqsh ichkariga botdi, panel surilib, kalit teshigi koʻrindi."),
("msg.compartment", "A hidden compartment slides out of the desk.", "Из стола выдвигается тайник.", "Stoldan yashirin boʻlma chiqib keldi."),
("msg.main_no_handle", "The main breaker has no handle.", "У главного рубильника нет рукояти.", "Asosiy uzgichning dastasi yoʻq."),
("msg.handle_installed", "The handle clicks into place.", "Рукоять встаёт на место.", "Dasta joyiga oʻrnashdi."),
("msg.breaker_tripped", "Sparks! The VENT line tripped the breaker.", "Искры! Линия вентиляции выбила рубильник.", "Uchqunlar! Shamollatish liniyasi uzgichni urib tushirdi."),
("msg.power_restored", "Power restored.", "Питание восстановлено.", "Elektr tiklandi."),
("msg.switches_locked", "The circuit is locked in place.", "Цепь зафиксирована.", "Zanjir mahkamlangan."),
("msg.main_locked", "The main lever is locked in place.", "Главный рычаг зафиксирован.", "Asosiy dastak mahkamlangan."),
("msg.radio_dead", "The radio is silent.", "Радио молчит.", "Radio jim."),
("msg.radio_no_power", "No power reaches the radio.", "Радио обесточено.", "Radioga tok kelmayapti."),
("msg.radio_needs_valve", "The hatch reveals an empty valve socket.", "Под крышкой — пустое гнездо для лампы.", "Qopqoq ostida lampa uchun boʻsh uyacha bor."),
("msg.valve_installed", "The valve warms up with an orange glow.", "Лампа разогревается оранжевым светом.", "Lampa qizib, toʻq sariq nur sochdi."),
("msg.radio_signal", "A signal cuts through the static…", "Сквозь помехи пробивается сигнал…", "Shovqin orasidan signal eshitildi…"),
("msg.shelf_opened", "Something clicks behind the books… the bookcase swings open!", "За книгами что-то щёлкает… шкаф отъезжает в сторону!", "Kitoblar ortida nimadir chiqilladi… javon ochilib ketdi!"),
("msg.red_glow", "A faint red glow seeps around the bookcase.", "Вокруг книжного шкафа сочится слабый красный свет.", "Kitob javoni atrofidan xira qizil nur sizib chiqyapti."),
("msg.cabinet_opened", "The shadow forms the mark — the cabinet clicks open.", "Тень складывается в знак — шкафчик открывается.", "Soya belgini hosil qildi — javoncha ochildi."),
("msg.emblem_recorded", "The crystal flares. It has remembered the mark.", "Кристалл вспыхивает. Он запомнил знак.", "Billur chaqnadi. U belgini eslab qoldi."),
("msg.lens_in_socket", "The lens fits the socket perfectly.", "Линза идеально встаёт в гнездо.", "Linza uyachaga aynan mos tushdi."),
("msg.lens_in_projector", "The crystal lens slides into the projector.", "Кристаллическая линза встаёт в проектор.", "Billur linza proyektorga joylashdi."),
("msg.projector_no_power", "The projector is dead. It needs power.", "Проектор мёртв. Нужно питание.", "Proyektor ishlamayapti. Unga tok kerak."),
("msg.projector_no_lens", "The lens socket is empty.", "Гнездо для линзы пусто.", "Linza uyachasi boʻsh."),
("msg.projector_scatter", "The light scatters — the rings are out of tune.", "Свет рассеивается — кольца не настроены.", "Yorugʻlik tarqalib ketdi — halqalar sozlanmagan."),
("msg.beam_on", "A clean Lumen beam pours from the lens.", "Из линзы льётся чистый луч Люмена.", "Linzadan musaffo Lumen nuri oqib chiqdi."),
("msg.rings_locked", "The rings won't move while the beam is on.", "Кольца не двигаются, пока горит луч.", "Nur yonib turganda halqalar qimirlamaydi."),
("msg.mirror_back", "The beam strikes the brass back of the mirror.", "Луч бьёт в латунную тыльную сторону зеркала.", "Nur koʻzguning jez orqa tomoniga urildi."),
("msg.lock_waits", "The beam reaches the door's eye… but it waits for a sign.", "Луч касается глаза двери… но он ждёт знака.", "Nur eshik koʻziga yetdi… lekin u belgi kutyapti."),
("msg.door_unlocked", "The door's eye blazes. The magnetic lock lets go.", "Глаз двери вспыхивает. Магнитный замок отпускает.", "Eshik koʻzi chaqnadi. Magnit qulf boʻshadi."),
("msg.mirror_mounted", "The mirror clicks onto the stand.", "Зеркало защёлкивается на стойке.", "Koʻzgu tirgakka mahkamlandi."),
("msg.lens_removed", "You take the crystal lens back.", "Вы забираете линзу обратно.", "Billur linzani qaytarib olasiz."),
("msg.book_pulled", "Volume %s tilts out, then springs back.", "Том %s наклоняется и возвращается на место.", "%s-jild egilib chiqdi va joyiga qaytdi."),
("msg.needs_uv", "Something here might show under the right light.", "Здесь что-то может проявиться при нужном свете.", "Bu yerda toʻgʻri yorugʻlikda nimadir koʻrinishi mumkin."),

# ---------------------------------------------------------------- feedback for taps on scenery and locked mechanisms (3D QA pass)
("msg.clock_stopped", "Stopped at 03:17. Nothing will turn it.", "Остановились на 03:17. Ничто их не сдвинет.", "03:17 da toʻxtab qolgan. Hech narsa uni yurgizmaydi."),
("msg.desk_clutter", "Cold tea, her spectacles, a magnifier. She left in a hurry.", "Остывший чай, её очки, лупа. Она уходила в спешке.", "Sovigan choy, uning koʻzoynagi, lupa. U shoshib ketgan."),
("msg.desk_side", "Carved oak panels and brass rosettes run along the side of the desk.", "Вдоль боковины стола — резные дубовые панели и латунные розетки.", "Stolning yon tomoni boʻylab oʻyma eman panellar va jez rozetkalar."),
("msg.box_locked", "The lid will not lift. Three gear wheels turn beneath it.", "Крышка не поднимается. Под ней вращаются три шестерни.", "Qopqoq koʻtarilmaydi. Uning ostida uchta tishli gʻildirak aylanadi."),
("msg.safe_locked", "Locked. Four digits on the keypad open it.", "Заперто. Его открывают четыре цифры на клавиатуре.", "Qulflangan. Uni klaviaturadagi toʻrtta raqam ochadi."),
("msg.panel_lamps", "Four indicator lamps. They answer the switches below.", "Четыре индикаторные лампы. Они отвечают переключателям внизу.", "Toʻrtta koʻrsatkich chiroq. Ular pastdagi tumblerlarga javob beradi."),
("msg.bench_glass", "Glassware, a microscope and three stoppered samples.", "Стеклянная посуда, микроскоп и три закупоренных образца.", "Shisha idishlar, mikroskop va uchta tiqinlangan namuna."),
("msg.coat_pockets", "A coat, still on its hook. The pockets look empty.", "Пальто всё ещё на вешалке. Карманы кажутся пустыми.", "Palto hamon ilgichda. Choʻntaklari boʻsh koʻrinadi."),
("msg.filing_locked", "The cabinet drawers are locked. Nothing rattles inside.", "Ящики картотеки заперты. Внутри ничего не гремит.", "Kartoteka tortmalari qulflangan. Ichida hech narsa shiqirlamaydi."),
("msg.chalkboard_dust", "Strand's hand. The formula has been rubbed out and rewritten more than once.", "Почерк Странда. Формулу стирали и переписывали не раз.", "Strandning dastxati. Formula bir necha bor oʻchirilib, qayta yozilgan."),
("msg.poster_table", "Strand's table of resonances: each symbol has its own count of dots.", "Таблица резонансов Странда: у каждого символа своё число точек.", "Strandning rezonanslar jadvali: har bir belgining oʻz nuqtalar soni bor."),
("msg.lock_dark", "A glass eye set into the door. It waits for light.", "Стеклянный глаз, вделанный в дверь. Он ждёт света.", "Eshikka oʻrnatilgan shisha koʻz. U yorugʻlikni kutadi."),

# ---------------------------------------------------------------- captions (sound → text, accessibility)
("cap.maglock", "[Magnetic lock clicks shut]", "[Щелчок магнитного замка]", "[Magnit qulf chiqillab yopildi]"),
("cap.beacon", "[Radio beacon: %s]", "[Радиомаяк: %s]", "[Radiomayoq: %s]"),
("cap.static", "[Radio static]", "[Радиопомехи]", "[Radio shovqini]"),
("cap.hum", "[The projector hums]", "[Проектор гудит]", "[Proyektor gʻuvillaydi]"),
("cap.sparks", "[Sparks crackle]", "[Треск искр]", "[Uchqunlar chirsillaydi]"),
("cap.door", "[The heavy door creaks open]", "[Тяжёлая дверь со скрипом открывается]", "[Ogʻir eshik gʻiyqillab ochildi]"),
]
