# -*- coding: utf-8 -*-
"""Chapter 4 "The Experiment" — the Array Hall. (key, en, ru, uz). Uzbek: Latin only, ʻ for oʻ/gʻ.
Puzzle-critical information is never carried by these texts alone (marks, minutes, numerals and the
needle are on the objects). Roman numerals and digits are plain text; symbols stay art."""

S = [
# ---------------------------------------------------------------- hint fragments (level-3 reversal schedule)
("hint.c4_act.sun", "the Sun lever off", "выключить Солнце", "Quyosh dastagini oʻchiring"),
("hint.c4_act.rings", "every ring back to mark 1", "все кольца на метку 1", "barcha halqalarni 1-belgiga qaytaring"),
("hint.c4_act.keeper", "the keeper knob to 0", "ручку хранения на 0", "saqlash murvatini 0 ga buring"),
# ---------------------------------------------------------------- items
("item.strand_key.desc4", "Heavy brass with a star. A second line on the tag: “— and below the Choir, the Hall.”", "Тяжёлая латунь со звездой. Вторая строка на бирке: «— а под Хором — Зал».", "Yulduzli ogʻir jez kalit. Yorliqdagi ikkinchi qator: «— Xor ostida esa — Zal»."),
("item.leyla_key.desc4", "Plain steel with a crescent. A second line on the tag: “— and below the Nursery, the Hall. Finish it.”", "Простая сталь с полумесяцем. Вторая строка на бирке: «— а под Питомником — Зал. Закончи».", "Yarim oyli oddiy poʻlat kalit. Yorliqdagi ikkinchi qator: «— Koʻchatxona ostida esa — Zal. Yakunla»."),
("item.tower_key_1.name", "Tower key I", "Ключ башни I", "I minora kaliti"),
("item.tower_key_1.desc", "A brass key stamped I. It fits the cage gate with the same numeral.", "Латунный ключ с клеймом I. Подходит к воротам клетки с той же цифрой.", "I tamgʻali jez kalit. Qafasning shu raqamli darvozasiga tushadi."),
("item.tower_key_2.name", "Tower key II", "Ключ башни II", "II minora kaliti"),
("item.tower_key_2.desc", "A brass key stamped II. It fits the cage gate with the same numeral.", "Латунный ключ с клеймом II. Подходит к воротам клетки с той же цифрой.", "II tamgʻali jez kalit. Qafasning shu raqamli darvozasiga tushadi."),
("item.tower_key_3.name", "Tower key III", "Ключ башни III", "III minora kaliti"),
("item.tower_key_3.desc", "A brass key stamped III. It fits the cage gate with the same numeral.", "Латунный ключ с клеймом III. Подходит к воротам клетки с той же цифрой.", "III tamgʻali jez kalit. Qafasning shu raqamli darvozasiga tushadi."),
("item.tower_key_4.name", "Tower key IV", "Ключ башни IV", "IV minora kaliti"),
("item.tower_key_4.desc", "A brass key stamped IV. It fits the cage gate with the same numeral.", "Латунный ключ с клеймом IV. Подходит к воротам клетки с той же цифрой.", "IV tamgʻali jez kalit. Qafasning shu raqamli darvozasiga tushadi."),
("item.strand_log.name", "Strand's log", "Журнал Странда", "Strandning jurnali"),
("item.strand_log.desc", "The log of the Night of Silence, in Strand's hand. The last entry is 03:17.", "Журнал Ночи тишины, рукой Странда. Последняя запись — 03:17.", "Sukunat kechasining jurnali, Strand qoʻli bilan. Oxirgi yozuv — 03:17."),
("item.pocket_watch.name", "Pocket watch", "Карманные часы", "Choʻntak soati"),
("item.pocket_watch.desc", "Strand's watch, stopped at 03:17. Engraved inside the lid: “E.S. — light remembers.”", "Часы Странда, остановились на 03:17. Гравировка под крышкой: «Э. С. — свет помнит».", "Strandning soati, 03:17 da toʻxtagan. Qopqogʻi ichida oʻyma: «E. S. — yorugʻlik eslaydi»."),
("item.strand_last_letter.name", "Strand's last letter", "Последнее письмо Странда", "Strandning soʻnggi maktubi"),
("item.strand_last_letter.desc", "To Leyla, written on the Night. It names the part he never dared to fit.", "Лейле, написано в ту Ночь. В нём названа деталь, которую он так и не решился поставить.", "Leylaga, oʻsha Kechada yozilgan. Unda u oʻrnatishga jurʼat etmagan detal nomi bor."),
("item.reverse_pawl.name", "Reverse pawl", "Обратная собачка", "Teskari ilgak"),
("item.reverse_pawl.desc", "A small brass escapement part. With it, a clock can run backwards.", "Маленькая латунная деталь хода. С ней часы могут идти назад.", "Soat yurgichining kichik jez detali. U bilan soat orqaga yura oladi."),
("item.leyla_note_1998.name", "Leyla's note, 1998", "Записка Лейлы, 1998", "Leylaning xati, 1998"),
("item.leyla_note_1998.desc", "A folded page from her locker, dated 1998.", "Сложенный листок из её шкафчика, датирован 1998 годом.", "Shkafchasidan olingan buklangan varaq, 1998-yil sanasi bilan."),
("item.leyla_parcel.name", "Leyla's parcel", "Посылка Лейлы", "Leylaning posilkasi"),
("item.leyla_parcel.desc", "Brown paper and string. Addressed to Laboratory 7 in Leyla's hand. No postmark yet.", "Коричневая бумага и бечёвка. Адрес рукой Лейлы: Лаборатория 7. Штемпеля пока нет.", "Qoʻngʻir qogʻoz va ip. Leyla qoʻli bilan yozilgan manzil: 7-laboratoriya. Pochta tamgʻasi hali yoʻq."),
# ---------------------------------------------------------------- places (view captions)
("obj4.lift", "Freight lift — the unnumbered floor", "Грузовой лифт — этаж без номера", "Yuk lifti — raqamsiz qavat"),
("obj4.bridge", "Operator's bridge", "Мостик оператора", "Operator koʻprigi"),
("obj4.desk", "Master desk", "Главный пульт", "Bosh pult"),
("obj4.chronometer", "Chronometer — 03:10 to 03:17", "Хронометр — от 03:10 до 03:17", "Xronometr — 03:10 dan 03:17 gacha"),
("obj4.handwheels", "Ring handwheels I–IV", "Штурвалы колец I–IV", "Halqa gʻildiraklari I–IV"),
("obj4.panel0", "Panel 0 — LOCK · LIGHT · ARRAY · VENT", "Щит 0 — ЗАМОК · СВЕТ · РЕШЁТКА · ВЕНТ", "0-panel — QULF · YORUGʻLIK · PANJARA · VENT"),
("obj4.catwalk", "Catwalk over the rings", "Мостик над кольцами", "Halqalar ustidagi yoʻlak"),
("obj4.hatch", "Hatch over ring %s", "Люк над кольцом %s", "%s halqa ustidagi lyuk"),
("obj4.island", "The Reliquary", "Реликварий", "Relikvariy"),
("obj4.gate", "Cage gate %s", "Ворота клетки %s", "Qafas darvozasi %s"),
("obj4.collar", "Collar lock", "Замковое кольцо", "Qulf halqasi"),
("obj4.core", "The Core", "Ядро", "Oʻzak"),
("obj4.apse", "The Sun apse", "Апсида Солнца", "Quyosh apsidasi"),
("obj4.sun_pedestal", "Sun pedestal — feed, ammeter, lever", "Пульт Солнца — подача, амперметр, рычаг", "Quyosh pulti — uzatish, ampermetr, dastak"),
("obj4.iris", "The iris", "Диафрагма", "Diafragma"),
("obj4.booth", "Strand's booth", "Кабина Странда", "Strandning kabinasi"),
("obj4.gear_box", "Strand's box", "Шкатулка Странда", "Strandning qutichasi"),
("obj4.watch", "The watch room", "Дежурная", "Navbatchi xonasi"),
("obj4.roll_board", "Roll board — 41 tags", "Доска переклички — 41 бирка", "Yoʻqlama taxtasi — 41 yorliq"),
("obj4.locker", "Locker 17", "Шкафчик 17", "17-shkafcha"),
("obj4.post_station", "Pneumatic post station", "Станция пневмопочты", "Pnevmatik pochta stansiyasi"),
("obj4.oculus", "The oculus", "Окулюс", "Gumbaz tuynugi"),
# ---------------------------------------------------------------- messages (msg.* = layout-tested)
("msg.c4_gate_wrong_key", "This gate takes the other key.", "Эти ворота открывает другой ключ.", "Bu darvozani boshqa kalit ochadi."),
("msg.c4_booth_locked", "The booth gate is locked.", "Ворота кабины заперты.", "Kabina darvozasi qulflangan."),
("msg.c4_watch_locked", "The grille is locked.", "Решётка дежурной заперта.", "Navbatchi xonasining panjarasi qulflangan."),
("msg.c4_apse_dark", "The apse is dark. The lamp waits for power.", "В апсиде темно. Лампа ждёт тока.", "Apsida qorongʻi. Chiroq tok kutmoqda."),
("msg.c4_catwalk_locked", "The catwalk gate holds while the lines are dead.", "Калитка мостика заперта, пока линии мертвы.", "Liniyalar jonsiz ekan, yoʻlak eshigi yopiq."),
("msg.c4_lines_dead", "A lamp is still dark. Strand's plate wants all four.", "Одна из ламп ещё темна. На табличке Странда — все четыре.", "Chiroqlardan biri hali qorongʻi. Strand lavhasida — toʻrttasi ham."),
("msg.c4_power_on", "Relays clack. Lamps wake ring by ring; high above, the oculus shutter grinds open.", "Щёлкают реле. Лампы загораются кольцо за кольцом; высоко вверху открывается окулюс.", "Relelar chiqillaydi. Chiroqlar halqa ketidan halqa yonadi; tepada gumbaz tuynugi ochiladi."),
("msg.c4_hall_powered", "The hall is running.", "Зал под напряжением.", "Zal tok ostida."),
("msg.c4_switches_locked", "The switches are locked live.", "Переключатели заблокированы под напряжением.", "Ulagichlar tok ostida qulflangan."),
("msg.c4_box_is_open", "The box is open. The little Array sits inside.", "Шкатулка открыта. Внутри — маленькая Решётка.", "Quticha ochiq. Ichida — kichkina Panjara."),
("msg.c4_box_open", "The lid rises: a tiny brass Array, its towers set, and Strand's log.", "Крышка поднимается: крошечная латунная Решётка с выставленными башнями и журнал Странда.", "Qopqoq koʻtariladi: minoralari oʻrnatilgan kichkina jez Panjara va Strandning jurnali."),
("msg.c4_rods_apart", "The rods stand apart. Nothing happens.", "Стержни разведены. Ничего не происходит.", "Tayoqchalar bir-biridan uzoq. Hech narsa boʻlmaydi."),
("msg.c4_arc_shorted", "The rods touch. The needle slams to the stop.", "Стержни касаются. Стрелка бьёт в упор.", "Tayoqchalar tegishdi. Mil toʻxtatgichga urildi."),
("msg.c4_arc_struck", "The arc strikes with a crack.", "Дуга вспыхивает с треском.", "Yoy chirsillab yonadi."),
("msg.c4_arc_out", "Too far: the arc snaps out.", "Слишком далеко: дуга гаснет.", "Juda uzoq: yoy uzilib oʻchdi."),
("msg.c4_sun_steady", "The needle sits in the green. The Sun burns steady.", "Стрелка в зелёной зоне. Солнце горит ровно.", "Mil yashil zonada. Quyosh bir tekis yonadi."),
("msg.c4_sun_flicker", "The arc flickers. The needle is off the green.", "Дуга дрожит. Стрелка вне зелёной зоны.", "Yoy lipillaydi. Mil yashil zonadan tashqarida."),
("msg.c4_sun_off", "The Sun goes dark.", "Солнце гаснет.", "Quyosh soʻndi."),
("msg.c4_leaf_pinned", "This leaf is held down by the one above it.", "Этот лепесток прижат тем, что лежит сверху.", "Bu yaproqni ustidagisi bosib turibdi."),
("msg.c4_iris_open", "The iris opens. A beam the width of a door crosses the hall.", "Диафрагма раскрывается. Луч шириной с дверь пересекает зал.", "Diafragma ochildi. Eshik kengligidagi nur zalni kesib oʻtadi."),
("msg.c4_wheels_dead", "The handwheels are stiff. The drive is dead.", "Штурвалы не идут. Привод мёртв.", "Gʻildiraklar qotib qolgan. Yuritma jonsiz."),
("msg.c4_beam_0", "The beam dies at the outer ring.", "Луч гаснет у внешнего кольца.", "Nur tashqi halqada soʻnadi."),
("msg.c4_beam", "The beam reaches tower %d.", "Луч доходит до башни %d.", "Nur %d-minoraga yetib boradi."),
("msg.c4_replay_on", "The beam folds into the Core. The hall fills with figures of light, frozen at 03:17.", "Луч складывается в Ядро. Зал заполняют фигуры света, застывшие в 03:17.", "Nur Oʻzakka buklanib kiradi. Zalni 03:17 da qotib qolgan nur siymolari toʻldiradi."),
("msg.c4_replay_off", "The beam breaks. The figures fade like breath.", "Луч обрывается. Фигуры тают, как дыхание.", "Nur uzildi. Siymolar nafas kabi tarqab ketadi."),
("msg.c4_replay_weak", "The beam slips straight through the gaps. The figures flicker and fade.", "Луч проскальзывает прямо в просветы. Фигуры мерцают и тают.", "Nur oraliqlardan toʻppa-toʻgʻri sirgʻalib oʻtadi. Siymolar lipillab soʻnadi."),
("msg.c4_chrono_locked", "The wheel is clutched to the Array. It turns only while the hall replays.", "Колесо сцеплено с Решёткой. Оно крутится, только пока зал повторяет.", "Gʻildirak Panjaraga ulangan. U faqat zal takrorlayotganda aylanadi."),
("msg.c4_minute", "03:1%d.", "03:1%d.", "03:1%d."),
("msg.c4_tower_out_of_reach", "The key is on the tower, out of reach. Bring the tower under the hatch.", "Ключ на башне, не достать. Подведите башню под люк.", "Kalit minorada, qoʻl yetmaydi. Minorani lyuk tagiga keltiring."),
("msg.c4_key_wrong_gate", "This key fits another gate.", "Этот ключ от других ворот.", "Bu kalit boshqa darvozaga tushadi."),
("msg.c4_gate_open", "The gate unlocks. The key stays in it.", "Ворота отпираются. Ключ остаётся в замке.", "Darvoza ochildi. Kalit qulfda qoladi."),
("msg.c4_cage_open", "The cage swings open around the glass tower.", "Клетка раскрывается вокруг стеклянной башни.", "Qafas shisha minora atrofida ochildi."),
("msg.c4_collar_shut", "The collar holds the tower shut.", "Замковое кольцо держит башню закрытой.", "Qulf halqasi minorani yopiq tutib turibdi."),
("msg.c4_tower_open", "The glass panels sink into the floor. The Core, bare.", "Стеклянные панели уходят в пол. Ядро — обнажено.", "Shisha panellar polga choʻkadi. Oʻzak — yalangʻoch."),
("msg.c4_cradle_refused", "The socket is cut for the crystal lens.", "Гнездо вырезано под кристаллическую линзу.", "Uyacha billur linza uchun oʻyilgan."),
("msg.c4_cradle_full", "The cradle already holds the lens.", "В гнезде уже лежит линза.", "Uyachada linza allaqachon bor."),
("msg.c4_lens_seated", "The lens seats. The Core's light passes through it.", "Линза встаёт на место. Свет Ядра проходит сквозь неё.", "Linza oʻrniga tushdi. Oʻzak nuri undan oʻtadi."),
("msg.c4_heart_open", "The Institute's mark falls on the drawer's face. It slides open.", "Знак института ложится на лицевую панель ящика. Ящик выдвигается.", "Institut belgisi tortma yuziga tushadi. Tortma surilib ochiladi."),
("msg.c4_lens_taken", "The lens is warm in your hand. The mark fades from the drawer.", "Линза тёплая в руке. Знак на ящике гаснет.", "Linza qoʻlingizda iliq. Tortmadagi belgi soʻnadi."),
("msg.c4_pawl_fitted", "The pawl clicks into the escapement. The clock can run both ways.", "Собачка щёлкает в механизме хода. Часы могут идти в обе стороны.", "Ilgak yurgichga chiq etib tushdi. Soat ikki tomonga yura oladi."),
("msg.c4_desk_dead", "The desk is dead.", "Пульт мёртв.", "Pult jonsiz."),
("msg.c4_beat_far", "Two notes beat fast against each other.", "Две ноты быстро бьются друг о друга.", "Ikki nota bir-biriga tez uriladi."),
("msg.c4_beat_near", "The beat slows.", "Биение замедляется.", "Tepish sekinlashadi."),
("msg.c4_keeper_on", "The notes lock. The Core answers with a held chord.", "Ноты сливаются. Ядро отвечает долгим аккордом.", "Notalar qoʻshildi. Oʻzak choʻziq akkord bilan javob beradi."),
("msg.c4_keeper_off", "The keeper is off. The Core hums alone.", "Хранение выключено. Ядро гудит само.", "Saqlash oʻchiq. Oʻzak oʻzicha gʻuvillaydi."),
("msg.c4_master_held", "The lever is held fast. Everything must stand as on the Night, at 03:17, with a clock that can run back.", "Рычаг заперт. Всё должно стоять как в ту Ночь, в 03:17, и часы должны уметь идти назад.", "Dastak qotib turibdi. Hammasi oʻsha Kechadagidek, 03:17 da boʻlsin, va soat orqaga yura olsin."),
("msg.c4_reversal_begins", "The lever lifts. Across the hall the frozen figures begin to move — backwards.", "Рычаг поднимается. По всему залу застывшие фигуры начинают двигаться — назад.", "Dastak koʻtarildi. Zal boʻylab qotib qolgan siymolar harakatlana boshlaydi — orqaga."),
("msg.c4_held_fast", "Held fast. Not this minute.", "Не поддаётся. Не в эту минуту.", "Qotib turibdi. Bu daqiqada emas."),
("msg.c4_wound", "03:1%d. The hall remembers a minute less.", "03:1%d. Зал помнит на минуту меньше.", "03:1%d. Zal bir daqiqa kamroq eslaydi."),
("msg.c4_snap_back", "The Array holds. Every lever slams down, the rings grind back, the Sun relights. 03:17.", "Решётка держит. Все рычаги падают, кольца со скрежетом возвращаются, Солнце вспыхивает снова. 03:17.", "Panjara ushlab turadi. Barcha dastaklar tushadi, halqalar gʻijirlab qaytadi, Quyosh yana yonadi. 03:17."),
("msg.c4_night_undone", "The hall is dark, and forty-one lights rise through the oculus.", "В зале темно, и сорок один огонь поднимается сквозь окулюс.", "Zal qorongʻi, va qirq bitta chiroq gumbaz tuynugidan koʻtariladi."),
("msg.c4_station_dead", "The station is dead.", "Станция мертва.", "Stansiya jonsiz."),
("msg.c4_canister_empty", "The canister is empty.", "Капсула пуста.", "Kapsula boʻsh."),
("msg.c4_canister_full", "The canister already holds something.", "В капсуле уже что-то есть.", "Kapsulada allaqachon nimadir bor."),
("msg.c4_canister_loaded", "The parcel fits the canister exactly.", "Посылка входит в капсулу точно по размеру.", "Posilka kapsulaga aynan sigʻadi."),
("msg.c4_post_no_receiver", "A rush, then a knock from far above: no one receives. The canister drops back.", "Шум воздуха, потом стук далеко вверху: никто не принимает. Капсула падает обратно.", "Havo shovqini, keyin yuqoridan taqillash: hech kim qabul qilmaydi. Kapsula qaytib tushadi."),
("msg.c4_post_returned", "The canister comes back. Wrong address.", "Капсула возвращается. Неверный адрес.", "Kapsula qaytib keldi. Manzil notoʻgʻri."),
("msg.c4_parcel_sent", "The canister leaves and does not come back. Somewhere, a postmark: 14 November 1979.", "Капсула уходит и не возвращается. Где-то ставят штемпель: 14 ноября 1979.", "Kapsula ketdi va qaytmadi. Qayerdadir tamgʻa bosiladi: 1979-yil 14-noyabr."),
("msg.c4_locker_bare", "Leyla's locker: a coat, a note, nothing more.", "Шкафчик Лейлы: халат, записка, больше ничего.", "Leylaning shkafchasi: xalat, xat, boshqa hech narsa."),
("msg.c4_echo_count", "Kept echoes released: %d / 4", "Освобождено эхо: %d / 4", "Ozod qilingan aks-sadolar: %d / 4"),
# ---------------------------------------------------------------- captions (sound + story)
("cap4.lift", "[The lift stops at a floor with no number]", "[Лифт останавливается на этаже без номера]", "[Lift raqamsiz qavatda toʻxtaydi]"),
("cap4.power", "[Relays clack. Work lamps wake, ring by ring]", "[Щёлкают реле. Рабочие лампы загораются кольцо за кольцом]", "[Relelar chiqillaydi. Ish chiroqlari halqa ketidan halqa yonadi]"),
("cap4.arc", "[The arc strikes with a crack and a hiss]", "[Дуга вспыхивает с треском и шипением]", "[Yoy chirsillab, vishillab yonadi]"),
("cap4.iris", "[Six brass leaves lift, one after another]", "[Шесть латунных лепестков поднимаются один за другим]", "[Oltita jez yaproq birin-ketin koʻtariladi]"),
("cap4.rings", "[Steel rings grind on their rails]", "[Стальные кольца скрежещут по рельсам]", "[Poʻlat halqalar relslarda gʻijirlaydi]"),
("cap4.replay", "[The hall fills with figures of light, frozen]", "[Зал заполняют застывшие фигуры света]", "[Zalni qotib qolgan nur siymolari toʻldiradi]"),
("cap4.strand_desk", "Strand stands at the master desk, one hand on the lever, frozen in the moment he pulled it.", "Странд стоит у главного пульта, рука на рычаге, застывший в миг, когда он его потянул.", "Strand bosh pult yonida turibdi, qoʻli dastakda, uni tortgan lahzada qotib qolgan."),
("cap4.forty_second", "Inside the Core, a forty-second light turns toward you.", "Внутри Ядра сорок второй огонь поворачивается к вам.", "Oʻzak ichida qirq ikkinchi chiroq sizga yuzlanadi."),
("cap4.leyla_lens", "Leyla steps out of the light, 1998. She seats the lens you left for her, and fades.", "Лейла выходит из света — 1998 год. Она ставит линзу, которую вы ей оставили, и тает.", "Leyla yorugʻlikdan chiqadi — 1998-yil. U siz qoldirgan linzani oʻrniga qoʻyadi va yoʻqoladi."),
("cap4.snap", "[Every lever slams down. 03:17]", "[Все рычаги падают. 03:17]", "[Barcha dastaklar tushadi. 03:17]"),
("cap4.rise", "[Forty-one lights rise]", "[Сорок один огонь поднимается]", "[Qirq bitta chiroq koʻtariladi]"),
("intro4.strand_key", "The freight lift sinks past Level −2. On the tag of Strand's key, a second line you never noticed: “— and below the Choir, the Hall.”", "Грузовой лифт опускается ниже уровня −2. На бирке ключа Странда — вторая строка, которой вы раньше не замечали: «— а под Хором — Зал».", "Yuk lifti −2-qavatdan ham pastga tushmoqda. Strand kalitining yorligʻida ilgari sezmagan ikkinchi qator: «— Xor ostida esa — Zal»."),
("intro4.leyla_key", "The freight lift sinks past Level −2. On the tag of Leyla's key, a second line you never noticed: “— and below the Nursery, the Hall. Finish it.”", "Грузовой лифт опускается ниже уровня −2. На бирке ключа Лейлы — вторая строка, которой вы раньше не замечали: «— а под Питомником — Зал. Закончи».", "Yuk lifti −2-qavatdan ham pastga tushmoqda. Leyla kalitining yorligʻida ilgari sezmagan ikkinchi qator: «— Koʻchatxona ostida esa — Zal. Yakunla»."),
("intro4.2", "The Array Hall. Every clock in the Institute stopped here, at 03:17.", "Зал Решётки. Все часы института остановились здесь, в 03:17.", "Panjara zali. Institutdagi barcha soatlar shu yerda, 03:17 da toʻxtagan."),
# ---------------------------------------------------------------- documents
("doc4.chalk", "L.R. 1998 — this time, all four.", "Л. Р. 1998 — в этот раз все четыре.", "L. R. 1998 — bu safar toʻrttasi ham."),
("doc4.log", "Tonight: the Sun, the rings and the Choir's note, each in its minute, and my hand on the lever at 03:17.\nI have sealed the Core and set its collar to the minute the Sun is lit. If anyone must open it again, let it be someone who watched.", "Сегодня ночью: Солнце, кольца и нота Хора, каждое в свою минуту, и моя рука на рычаге в 03:17.\nЯ запечатал Ядро и выставил его замковое кольцо на минуту, когда зажжётся Солнце. Если кому-то придётся открыть его снова — пусть это будет тот, кто смотрел.", "Bu kecha: Quyosh, halqalar va Xor notasi, har biri oʻz daqiqasida, va 03:17 da dastakdagi qoʻlim.\nOʻzakni muhrlab, qulf halqasini Quyosh yonadigan daqiqaga qoʻydim. Agar kimdir uni yana ochishi kerak boʻlsa — bu kuzatgan odam boʻlsin."),
("doc4.letter", "Leyla — I made the pawl that lets the clock run back. I never dared to fit it. If you are reading this, you dared more than I did.\nLet them go. Leave me the light.\n— E.S.", "Лейла — я сделал собачку, с которой часы пойдут назад. Я так и не решился её поставить. Если ты это читаешь, ты решилась на большее, чем я.\nОтпусти их. Оставь мне свет.\n— Э. С.", "Leyla — men soatni orqaga yurgizadigan ilgakni yasadim. Uni oʻrnatishga jurʼat etmadim. Agar buni oʻqiyotgan boʻlsang, sen mendan koʻra koʻproq jurʼat qilding.\nUlarni qoʻyib yubor. Menga yorugʻlikni qoldir.\n— E. S."),
("doc4.watch", "E.S. — light remembers", "Э. С. — свет помнит", "E. S. — yorugʻlik eslaydi"),
("doc4.note", "If the post still runs when time runs back, send it to the laboratory. You know which one.\n— L.R., 1998", "Если почта ещё работает, когда время пойдёт назад, отправь это в лабораторию. Ты знаешь, в какую.\n— Л. Р., 1998", "Agar vaqt orqaga yurganda pochta hali ishlasa, buni laboratoriyaga joʻnat. Qaysi biriga — oʻzing bilasan.\n— L. R., 1998"),
("doc4.parcel", "Laboratory 7.", "Лаборатория 7.", "7-laboratoriya."),
# ---------------------------------------------------------------- kept echoes
("echo4.tech_panel", "A technician kneels at Panel 0 with a lamp in his teeth, tracing a line with his finger.", "Техник стоит на коленях у щита 0 с фонариком в зубах и ведёт пальцем по линии.", "Texnik 0-panel oldida tiz choʻkib, tishida fonar, barmogʻi bilan chiziqni kuzatadi."),
("echo4.tech_wheels", "Two technicians lean on the handwheels, counting marks to each other.", "Двое техников налегли на штурвалы и считают метки друг другу.", "Ikki texnik gʻildiraklarga suyanib, bir-biriga belgilarni sanaydi."),
("echo4.clerk_post", "A clerk loads a canister at the post station and looks at the clock.", "Делопроизводитель заряжает капсулу на станции пневмопочты и смотрит на часы.", "Kotib pochta stansiyasida kapsulani joylab, soatga qaraydi."),
("echo4.leyla_lift", "Leyla steps out of the lift, 1998, a lamp in one hand and the crystal lens in the other.", "Лейла выходит из лифта — 1998 год, в одной руке лампа, в другой кристаллическая линза.", "Leyla liftdan chiqadi — 1998-yil, bir qoʻlida chiroq, ikkinchisida billur linza."),
# ---------------------------------------------------------------- finale + epilogue
("ui.choice_lens4_prompt", "The forty-one are gone into the morning. The crystal lens is still warm in the cradle.", "Сорок один ушли в утро. Кристаллическая линза всё ещё тёплая в гнезде.", "Qirq bir kishi tongga ketdi. Billur linza uyachada hali ham iliq."),
("ui.lens4_take", "Take the lens", "Забрать линзу", "Linzani olish"),
("ui.lens4_leave", "Leave it in the Core", "Оставить в Ядре", "Oʻzakda qoldirish"),
("epi4.dawn", "Forty-one lights rise through the oculus into the morning. A forty-second stays, by its own choice; it turns toward you once, then looks up.", "Сорок один огонь поднимается сквозь окулюс в утро. Сорок второй остаётся — по своей воле; он один раз поворачивается к вам, потом смотрит вверх.", "Qirq bitta chiroq gumbaz tuynugidan tongga koʻtariladi. Qirq ikkinchisi oʻz xohishi bilan qoladi; u bir bor sizga yuzlanadi, soʻng yuqoriga qaraydi."),
("epi4.keeper", "Forty lights rise through the oculus. One settles back into the Core and hums a single held note, softly: Strand, keeping the light he could not let go. A forty-second stays beside it and turns toward you.", "Сорок огней поднимаются сквозь окулюс. Один опускается обратно в Ядро и тихо тянет одну долгую ноту: Странд, хранящий свет, который не смог отпустить. Сорок второй остаётся рядом и поворачивается к вам.", "Qirq chiroq gumbaz tuynugidan koʻtariladi. Bittasi Oʻzakka qaytib choʻkadi va mayin, choʻziq bir nota taratadi: Strand — qoʻyib yubora olmagan yorugʻlikni saqlab. Qirq ikkinchisi uning yonida qoladi va sizga yuzlanadi."),
("epi4.true", "Forty-one lights rise through the oculus. The forty-second rises last. It pauses at the rim and looks at you the way it did in Laboratory 7.", "Сорок один огонь поднимается сквозь окулюс. Сорок второй поднимается последним. Он замирает у края и смотрит на вас так же, как смотрел в Лаборатории 7.", "Qirq bitta chiroq gumbaz tuynugidan koʻtariladi. Qirq ikkinchisi eng oxirida koʻtariladi. U chekkada toʻxtab, sizga 7-laboratoriyadagidek qaraydi."),
("epi4.strand_stays", "One light does not follow. It settles into the Core and hums a single held note, softly: Strand, a keeper by his own wish.", "Один огонь не следует за остальными. Он опускается в Ядро и тихо тянет одну долгую ноту: Странд, хранитель по собственной воле.", "Bir chiroq boshqalarga ergashmaydi. U Oʻzakka choʻkib, mayin, choʻziq bir nota taratadi: Strand — oʻz xohishi bilan saqlovchi."),
("epi4.parcel", "Far above, a brass canister drops into the dead station of Laboratory 7. Brown paper, string, a 1979 postmark. It will wait for you.", "Далеко вверху латунная капсула падает в мёртвую станцию Лаборатории 7. Коричневая бумага, бечёвка, штемпель 1979 года. Она будет ждать вас.", "Yuqorida, jez kapsula 7-laboratoriyaning jonsiz stansiyasiga tushadi. Qoʻngʻir qogʻoz, ip, 1979-yil tamgʻasi. U sizni kutadi."),
("epi4.lens_taken", "The crystal lens is warm in your hand. The Core goes dark behind you, and the hall is only a hall.", "Кристаллическая линза тёплая в руке. Ядро гаснет за вашей спиной, и зал — просто зал.", "Billur linza qoʻlingizda iliq. Oʻzak ortingizda soʻnadi, va zal — shunchaki zal."),
("epi4.lens_left", "The crystal lens stays in the cradle. The Core glows softly and replays ordinary days: a tea break, a chalkboard, a child's drawing. Light remembers.", "Кристаллическая линза остаётся в гнезде. Ядро мягко светится и повторяет обычные дни: перерыв на чай, доску, детский рисунок. Свет помнит.", "Billur linza uyachada qoladi. Oʻzak mayin yonib, odatiy kunlarni takrorlaydi: choy tanaffusi, doska, bola chizgan rasm. Yorugʻlik eslaydi."),
("epi4.echoes", "Four more kept echoes walked free before the Night was undone.", "Ещё четыре сохранённых эха вышли на свободу прежде, чем Ночь была отменена.", "Kecha bekor qilinishidan oldin yana toʻrtta saqlangan aks-sado ozod boʻldi."),
("epi4.all_light", "Every shard found, every echo released. Nothing the Institute kept is kept against its will.", "Все осколки найдены, все эхо освобождены. Ничто из того, что хранил институт, не удерживается против воли.", "Barcha boʻlaklar topildi, barcha aks-sadolar ozod qilindi. Institut saqlagan hech narsa oʻz xohishiga qarshi saqlanmayapti."),
("epi4.end", "Every clock in the building reads 03:13, and ticks. The Institute is no longer forgotten.", "Все часы в здании показывают 03:13 — и идут. Институт больше не забыт.", "Binodagi barcha soatlar 03:13 ni koʻrsatadi — va yuradi. Institut endi unutilgan emas."),
("achv.collect_ch4", "Echoes of the Hall", "Эхо Зала", "Zal aks-sadolari"),
]

H = {
"c4_power": [
    ("The hall is dead.", "Зал мёртв.", "Zal jonsiz."),
    ("The panel under the bridge: Strand's plate wants every lamp lit. Follow the engraved traces.", "Щит под мостиком: табличка Странда требует зажечь все лампы. Следуйте гравированным линиям.", "Koʻprik ostidagi panel: Strand lavhasi barcha chiroqlar yonishini talab qiladi. Oʻyilgan chiziqlarni kuzating."),
    ("Switches %s up, then the main lever.", "Переключатели %s вверх, затем главный рычаг.", "%s ulagichlarni yuqoriga, soʻng bosh dastakni."),
],
"c4_box": [
    ("Strand's box waits on his desk.", "Шкатулка Странда ждёт на его столе.", "Strandning qutichasi stolida kutmoqda."),
    ("Each knob drags the next gear along; the last turns alone. Start with the first knob.", "Каждая ручка тянет за собой следующую шестерню; последняя крутится одна. Начните с первой ручки.", "Har bir murvat keyingi gʻildirakni ham aylantiradi; oxirgisi yolgʻiz aylanadi. Birinchi murvatdan boshlang."),
    ("Press the knobs: first ×%d, second ×%d, third ×%d, fourth ×%d.", "Нажмите ручки: первую ×%d, вторую ×%d, третью ×%d, четвёртую ×%d.", "Murvatlarni bosing: birinchi ×%d, ikkinchi ×%d, uchinchi ×%d, toʻrtinchi ×%d."),
],
"c4_sun": [
    ("The Sun is cold.", "Солнце холодное.", "Quyosh sovuq."),
    ("Lever on. Feed the rods together until the needle slams over, then back them off into the green.", "Рычаг вверх. Сводите стержни, пока стрелка не ударит в упор, затем разводите их до зелёной зоны.", "Dastakni yoqing. Mil toʻxtatgichga urilguncha tayoqchalarni yaqinlashtiring, soʻng yashil zonagacha orqaga qaytaring."),
    ("Rods to 0, then back to %d.", "Стержни на 0, затем обратно на %d.", "Tayoqchalarni 0 ga, soʻng orqaga %d ga."),
],
"c4_iris": [
    ("The Sun burns behind its iris.", "Солнце горит за диафрагмой.", "Quyosh diafragma ortida yonmoqda."),
    ("A leaf under another will not lift. Start from the top of the stack.", "Лепесток под другим не поднимется. Начните с самого верхнего.", "Boshqasining tagidagi yaproq koʻtarilmaydi. Eng ustkisidan boshlang."),
    ("Leaves %s.", "Лепестки %s.", "Yaproqlar %s."),
],
"c4_align": [
    ("The beam stops at the rings.", "Луч останавливается у колец.", "Nur halqalarda toʻxtaydi."),
    ("The little Array in Strand's box shows where each tower stood. Each wheel drags the next ring: work from the outer ring in.", "Маленькая Решётка в шкатулке Странда показывает, где стояла каждая башня. Каждый штурвал тянет следующее кольцо: идите от внешнего кольца внутрь.", "Strand qutichasidagi kichkina Panjara har bir minora qayerda turganini koʻrsatadi. Har bir gʻildirak keyingi halqani ham tortadi: tashqi halqadan ichkariga boring."),
    ("Towers I to IV at marks %s.", "Башни с I по IV на метках %s.", "I–IV minoralar %s belgilarda."),
],
"c4_keys": [
    ("The cage has four locks.", "На клетке четыре замка.", "Qafasda toʻrtta qulf bor."),
    ("Each tower carries its gate's key. Bring a tower to mark 1 and reach it through the hatch in the catwalk.", "На каждой башне — ключ от её ворот. Подведите башню к метке 1 и достаньте ключ через люк в мостике.", "Har bir minorada oʻz darvozasining kaliti bor. Minorani 1-belgiga keltiring va kalitni yoʻlakdagi lyuk orqali oling."),
    ("Turn each ring to mark 1 in turn, outer first, and take the key below the hatch.", "Поочерёдно ставьте каждое кольцо на метку 1, начиная с внешнего, и берите ключ под люком.", "Har bir halqani navbat bilan, tashqisidan boshlab, 1-belgiga qoʻying va lyuk tagidagi kalitni oling."),
],
"c4_cage": [
    ("Four keys, four gates.", "Четыре ключа, четыре ворот.", "Toʻrt kalit, toʻrt darvoza."),
    ("The numerals match.", "Цифры совпадают.", "Raqamlar mos keladi."),
    ("Each key into the gate with its numeral.", "Каждый ключ — в ворота с его цифрой.", "Har bir kalitni oʻz raqamli darvozaga."),
],
"c4_collar": [
    ("Strand sealed the Core.", "Странд запечатал Ядро.", "Strand Oʻzakni muhrlagan."),
    ("“…its collar to the minute the Sun is lit.” Scrub the chronometer and watch for the Sun.", "«…замковое кольцо на минуту, когда зажжётся Солнце». Крутите хронометр и следите за Солнцем.", "«…qulf halqasini Quyosh yonadigan daqiqaga». Xronometrni aylantiring va Quyoshni kuzating."),
    ("%d-%d-%d-%d.", "%d-%d-%d-%d.", "%d-%d-%d-%d."),
],
"c4_lens": [
    ("The cradle has an empty socket.", "В гнезде пустая выемка.", "Uyachada boʻsh oʻrin bor."),
    ("The crystal lens fits it. The drawer below opens for the Institute's mark.", "Кристаллическая линза подходит к ней. Ящик внизу открывается на знак института.", "Billur linza unga tushadi. Pastdagi tortma institut belgisiga ochiladi."),
    ("Seat the crystal lens in the cradle.", "Вставьте кристаллическую линзу в гнездо.", "Billur linzani uyachaga qoʻying."),
],
"c4_pawl": [
    ("Strand made a part he never fitted.", "Странд сделал деталь, которую так и не поставил.", "Strand oʻrnatmagan bir detal yasagan."),
    ("Take the pawl from the drawer. The chronometer's back is open.", "Возьмите собачку из ящика. Задняя крышка хронометра открыта.", "Tortmadan ilgakni oling. Xronometrning orqa qopqogʻi ochiq."),
    ("Use the reverse pawl on the chronometer.", "Используйте обратную собачку на хронометре.", "Teskari ilgakni xronometrga qoʻying."),
],
"c4_note": [
    ("The Core hums a note of its own.", "Ядро гудит своей нотой.", "Oʻzak oʻz notasida gʻuvillaydi."),
    ("Turn the keeper knob and watch the beat on the oscillograph: slower is closer.", "Крутите ручку хранения и следите за биением на осциллографе: медленнее — значит ближе.", "Saqlash murvatini buring va ossillografdagi tepishni kuzating: sekinroq — demak yaqinroq."),
    ("Keeper at %d.", "Ручка хранения на %d.", "Saqlash murvati %d da."),
],
"c4_reversal": [
    ("Run the Night backwards.", "Прокрутите Ночь назад.", "Kechani orqaga aylantiring."),
    ("Everything as on the Night: the beam folded into the Core, the keeper on, the lens seated. Lift the master lever at 03:17. Then wind back a minute at a time, undoing each minute's step before you wind.", "Всё как в ту Ночь: луч сложен в Ядро, хранение включено, линза на месте. Поднимите главный рычаг в 03:17. Затем отводите время назад по минуте, отменяя шаг каждой минуты перед тем, как крутить дальше.", "Hammasi oʻsha Kechadagidek: nur Oʻzakka buklangan, saqlash yoqilgan, linza oʻrnida. 03:17 da bosh dastakni koʻtaring. Soʻng vaqtni daqiqa-daqiqa orqaga buring, har daqiqa qadamini burashdan oldin bekor qiling."),
    ("Lever at 03:17. Then at 03:1%d %s, at 03:1%d %s, at 03:1%d %s.", "Рычаг в 03:17. Затем в 03:1%d — %s, в 03:1%d — %s, в 03:1%d — %s.", "Dastak 03:17 da. Soʻng 03:1%d da %s, 03:1%d da %s, 03:1%d da %s."),
],
"c4_finale": [
    ("The lens is still in the cradle.", "Линза всё ещё в гнезде.", "Linza hali ham uyachada."),
    ("Take it, or leave it.", "Заберите её — или оставьте.", "Oling — yoki qoldiring."),
    ("Choose.", "Выбирайте.", "Tanlang."),
],
}
