# -*- coding: utf-8 -*-
"""Core strings: (key, en, ru, uz). Uzbek is Latin only, using ʻ (U+02BB) for oʻ/gʻ and ʼ (U+02BC).
Order of languages is fixed: EN (default) → RU → UZ."""

S = [
# ---------------------------------------------------------------- brand / chapters
("game.title", "MYSTERY ROOM", "MYSTERY ROOM", "MYSTERY ROOM"),
("game.subtitle", "The Forgotten Institute", "Забытый институт", "Unutilgan institut"),
("chapter.label", "Chapter %d", "Глава %d", "%d-bob"),
("chapter.ch1.title", "The Locked Laboratory", "Запертая лаборатория", "Qulflangan laboratoriya"),
("chapter.ch1.subtitle", "Laboratory 7", "Лаборатория 7", "7-laboratoriya"),
("chapter.ch2.title", "The Missing Scientist", "Пропавший учёный", "Gʻoyib boʻlgan olim"),
("chapter.ch2.subtitle", "The Archive", "Архив", "Arxiv"),
("chapter.ch3.title", "The Underground Facility", "Подземный комплекс", "Yer osti majmuasi"),
("chapter.ch3.subtitle", "Below the Institute", "Под институтом", "Institut ostida"),
("chapter.ch4.title", "The Experiment", "Эксперимент", "Tajriba"),
("chapter.ch4.subtitle", "The Array Hall", "Зал Решётки", "Panjara zali"),

# ---------------------------------------------------------------- main UI
("ui.continue", "Continue", "Продолжить", "Davom etish"),
("ui.new_game", "New Game", "Новая игра", "Yangi oʻyin"),
("ui.chapters", "Chapters", "Главы", "Boblar"),
("ui.settings", "Settings", "Настройки", "Sozlamalar"),
("ui.credits", "Credits", "Авторы", "Mualliflar"),
("ui.quit", "Quit", "Выход", "Chiqish"),
("ui.quit_confirm", "Quit the game? Your progress is saved.", "Выйти из игры? Прогресс сохранён.", "Oʻyindan chiqasizmi? Natijalar saqlangan."),
("ui.back", "Back", "Назад", "Orqaga"),
("ui.close", "Close", "Закрыть", "Yopish"),
("ui.resume", "Resume", "Продолжить", "Davom etish"),
("ui.pause", "Pause", "Пауза", "Pauza"),
("ui.main_menu", "Main Menu", "Главное меню", "Bosh menyu"),
("ui.yes", "Yes", "Да", "Ha"),
("ui.no", "No", "Нет", "Yoʻq"),
("ui.confirm", "Confirm", "Подтвердить", "Tasdiqlash"),
("ui.cancel", "Cancel", "Отмена", "Bekor qilish"),
("ui.on", "On", "Вкл.", "Yoniq"),
("ui.off", "Off", "Выкл.", "Oʻchiq"),
("ui.tap_to_continue", "Tap to continue", "Нажмите, чтобы продолжить", "Davom etish uchun bosing"),
("ui.skip", "Skip", "Пропустить", "Oʻtkazib yuborish"),
("ui.new_game_confirm", "Start a new game? Your current progress will be lost.", "Начать новую игру? Текущий прогресс будет потерян.", "Yangi oʻyin boshlansinmi? Joriy natijalar oʻchib ketadi."),
("ui.choose_language", "Choose your language", "Выберите язык", "Tilni tanlang"),
("ui.language", "Language", "Язык", "Til"),
("ui.music", "Music", "Музыка", "Musiqa"),
("ui.sfx", "Sound effects", "Звуковые эффекты", "Tovush effektlari"),
("ui.ambience", "Ambience", "Атмосфера", "Muhit tovushlari"),
("ui.text_size", "Text size", "Размер текста", "Matn oʻlchami"),
("ui.haptics", "Vibration", "Вибрация", "Tebranish"),
("ui.reduce_motion", "Reduce camera motion", "Меньше движения камеры", "Kamera harakatini kamaytirish"),
("ui.look_sensitivity", "Look sensitivity", "Чувствительность обзора", "Qarash sezgirligi"),
("ui.reset_settings", "Reset settings", "Сбросить настройки", "Sozlamalarni tiklash"),
("ui.delete_save", "Delete progress", "Удалить прогресс", "Natijalarni oʻchirish"),
("ui.delete_save_confirm", "Delete all saved progress? This cannot be undone.", "Удалить весь сохранённый прогресс? Это действие необратимо.", "Barcha saqlangan natijalar oʻchirilsinmi? Buni qaytarib boʻlmaydi."),
("ui.restore", "Restore purchases", "Восстановить покупки", "Xaridlarni tiklash"),
("ui.restored", "Purchases restored.", "Покупки восстановлены.", "Xaridlar tiklandi."),
("ui.privacy", "Privacy policy", "Политика конфиденциальности", "Maxfiylik siyosati"),
("ui.brightness", "Brightness", "Яркость", "Yorqinlik"),
("ui.unlock", "Unlock the full game", "Открыть полную игру", "Toʻliq oʻyinni ochish"),
("ui.unlock_desc", "One purchase unlocks every chapter. No ads, no subscriptions.", "Одна покупка открывает все главы. Без рекламы и подписок.", "Bitta xarid barcha boblarni ochadi. Reklama va obunasiz."),
("ui.store_unavailable", "The store is not available yet. New chapters are coming soon.", "Магазин пока недоступен. Новые главы скоро появятся.", "Doʻkon hozircha mavjud emas. Yangi boblar tez orada chiqadi."),
("ui.purchase_ok", "Thank you! The full game is unlocked.", "Спасибо! Полная игра открыта.", "Rahmat! Toʻliq oʻyin ochildi."),
("ui.free", "Free", "Бесплатно", "Bepul"),
("ui.locked", "Locked", "Закрыто", "Yopiq"),
("ui.coming_soon", "Coming soon", "Скоро", "Tez orada"),
("ui.completed", "Completed", "Пройдено", "Yakunlangan"),
("ui.play", "Play", "Играть", "Oʻynash"),
("ui.saved", "Progress saved", "Прогресс сохранён", "Jarayon saqlandi"),
("ui.save_failed", "Could not save progress", "Не удалось сохранить прогресс", "Jarayonni saqlab boʻlmadi"),
("ui.loading", "Loading…", "Загрузка…", "Yuklanmoqda…"),
("ui.version", "Version %s", "Версия %s", "Versiya %s"),

# ---------------------------------------------------------------- in-game HUD
("ui.hint", "Hint", "Подсказка", "Maslahat"),
("ui.hint_more", "Stronger hint", "Яснее", "Aniqroq"),
("ui.hint_level", "Hint %d of 3", "Подсказка %d из 3", "Maslahat: %d / 3"),
("ui.inspect", "Inspect", "Осмотреть", "Koʻrib chiqish"),
("ui.combine", "Combine", "Объединить", "Birlashtirish"),
("ui.use", "Use", "Использовать", "Ishlatish"),
("ui.read", "Read", "Читать", "Oʻqish"),
("ui.inventory_empty", "Your pockets are empty.", "Карманы пусты.", "Choʻntaklaringiz boʻsh."),
("ui.combine_prompt", "Tap an item to combine with: %s", "Выберите предмет для объединения с: %s", "Birlashtirish uchun buyumni tanlang: %s"),
("ui.use_prompt", "Tap where to use: %s", "Нажмите, где использовать: %s", "Qayerda ishlatishni tanlang: %s"),
("ui.uv_on", "UV light", "УФ-свет", "UB nur"),
("ui.uv_drag", "Drag to shine the UV lamp", "Ведите пальцем, чтобы светить УФ-лампой", "UB chiroqni yoritish uchun barmoqni suring"),
("ui.page", "Page %d / %d", "Стр. %d / %d", "%d / %d-sahifa"),
("ui.notebook", "Notebook", "Блокнот", "Daftar"),
("ui.journal", "Journal", "Журнал", "Jurnal"),
("ui.new_entry", "New note in the journal", "Новая запись в журнале", "Jurnalda yangi yozuv"),
("ui.item_added", "Found: %s", "Найдено: %s", "Topildi: %s"),
("ui.shard_found", "Lumen shard %d / 5", "Осколок Люмена %d / 5", "Lumen boʻlagi %d / 5"),
("ui.puzzle_solved", "Solved", "Решено", "Yechildi"),
("ui.choice_prompt", "The crystal lens hums softly in the projector. Leyla's light is fading.", "Кристаллическая линза тихо гудит в проекторе. Свет Лейлы угасает.", "Billur linza proyektorda sekin gʻuvillaydi. Leylaning nuri soʻnmoqda."),
("ui.take_lens", "Take the lens", "Забрать линзу", "Linzani olish"),
("ui.leave_lens", "Leave it for her", "Оставить её ей", "Unga qoldirish"),
("ui.chapter_complete", "Chapter complete", "Глава пройдена", "Bob yakunlandi"),
("ui.time", "Time", "Время", "Vaqt"),
("ui.hints_used", "Hints used", "Подсказок", "Maslahatlar"),
("ui.puzzles", "Puzzles solved", "Головоломок решено", "Yechilgan jumboqlar"),
("ui.shards", "Lumen shards", "Осколки Люмена", "Lumen boʻlaklari"),
("ui.next_chapter", "Next chapter", "Следующая глава", "Keyingi bob"),
("ui.to_be_continued", "To be continued…", "Продолжение следует…", "Davomi bor…"),
("ui.achievement", "Achievement: %s", "Достижение: %s", "Yutuq: %s"),
("ach.light_remembers", "Light Remembers", "Свет помнит", "Yorugʻlik eslaydi"),
("ach.no_hints_ch1", "Clear Mind", "Ясный ум", "Tiniq aql"),

# ---------------------------------------------------------------- onboarding
("tut.look", "Drag to look around.", "Проведите пальцем, чтобы осмотреться.", "Atrofga qarash uchun barmoqni suring."),
("tut.tap", "Tap objects to examine them.", "Нажимайте на предметы, чтобы рассмотреть их.", "Buyumlarni koʻrish uchun ularga bosing."),
("tut.zoom", "Pinch to zoom.", "Сведите пальцы, чтобы приблизить.", "Yaqinlashtirish uchun ikki barmoq bilan torting."),
("tut.back", "Tap the back arrow in the corner to step back.", "Нажмите стрелку «назад» в углу, чтобы вернуться.", "Orqaga qaytish uchun burchakdagi strelkani bosing."),
("tut.inventory", "Found items appear here. Tap to select, tap again to inspect.", "Найденные предметы появляются здесь. Нажмите, чтобы выбрать; ещё раз — чтобы осмотреть.", "Topilgan buyumlar shu yerda chiqadi. Tanlash uchun bosing, koʻrish uchun yana bosing."),
("tut.use", "With an item selected, tap the place where you want to use it.", "Выбрав предмет, нажмите туда, где хотите его использовать.", "Buyumni tanlab, uni ishlatmoqchi boʻlgan joyga bosing."),
("tut.combine", "Select an item, press Combine, then tap another item.", "Выберите предмет, нажмите «Объединить», затем другой предмет.", "Buyumni tanlang, «Birlashtirish»ni bosing, soʻng boshqa buyumni tanlang."),
("tut.hint", "Stuck? The lamp icon gives a hint — gently at first.", "Застряли? Значок лампы даст подсказку — сначала мягкую.", "Qiyin boʻldimi? Chiroq belgisi maslahat beradi — avval yengilroq."),

# ---------------------------------------------------------------- intro / outro
("intro.1", "Meridian Institute of Resonant Physics.\nSealed since 14 November 1979.", "Институт резонансной физики «Меридиан».\nЗакрыт с 14 ноября 1979 года.", "«Meridian» rezonans fizikasi instituti.\n1979-yil 14-noyabrdan beri yopiq."),
("intro.2", "A parcel came for you. Inside: an old laboratory badge and a single line.\n“Laboratory 7. Please finish what I could not.”", "Вам пришла посылка. Внутри — старый пропуск лаборатории и одна строка:\n«Лаборатория 7. Пожалуйста, закончи то, что не смогла я».", "Sizga posilka keldi. Ichida — eski laboratoriya guvohnomasi va bir qator yozuv:\n«7-laboratoriya. Iltimos, men tugata olmagan ishni tugating»."),
("outro.echo", "For a moment, the laboratory is 1979 again.", "На мгновение лаборатория снова в 1979 году.", "Bir lahzaga laboratoriya yana 1979-yilga qaytadi."),
("outro.listening", "The Array is listening again.", "Решётка снова слушает.", "Panjara yana tinglamoqda."),
("epi.take", "You pocket the crystal lens. It is warm — and somewhere far below, something answers its hum.", "Вы прячете линзу в карман. Она тёплая — и где-то глубоко внизу что-то отвечает на её гул.", "Billur linzani choʻntagingizga solasiz. U iliq — va qayerdadir chuqurda nimadir uning gʻuvillashiga javob beradi."),
("epi.leave", "You leave the lens to her. As the door closes behind you, the desk lamp flickers once, like a goodbye.", "Вы оставляете линзу ей. Когда дверь закрывается за вами, настольная лампа мигает — словно прощаясь.", "Linzani unga qoldirasiz. Eshik ortingizdan yopilganda stol chirogʻi bir bor miltillaydi — xuddi xayrlashgandek."),
("epi.shards", "Five shards — five fragments of a single night. The Array knows you now.", "Пять осколков — пять фрагментов одной ночи. Теперь Решётка знает вас.", "Beshta boʻlak — bitta tunning besh parchasi. Endi Panjara sizni taniydi."),
("epi.postmark", "On the train home you look at the parcel again. The postmark reads: 14 XI 1979.", "В поезде вы снова смотрите на посылку. На штемпеле: 14 XI 1979.", "Uyga qaytayotgan poyezdda posilkaga yana qaraysiz. Pochta muhrida: 14 XI 1979."),
]
